### ISSUE TITLE
[Bug]: Server crash: Zombie to player typecast?

### ISSUE THREAD

**Issue by joan7770** [TeamLapen/Vampirism#1026]
### Minecraft Version

1.16.x

### Forge Version

36.2.22

### Vampirism Version

1.8.5

### Singleplayer/Multiplayer

Server

### What happened?

Was in shader settings changing anti aliasing settings when all of a sudden the server crashed.
From my understanding of the log the crash happen on a typecast from the vampirism mod.
Crash report attached in the log section.

### Relevant log output

```shell
Time: 12/16/21, 12:41 AM
Description: Exception ticking world

java.lang.ClassCastException: class net.minecraft.entity.monster.ZombieEntity cannot be cast to class net.minecraft.entity.player.PlayerEntity (net.minecraft.entity.monster.ZombieEntity and net.minecraft.entity.player.PlayerEntity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @56dfab87)
	at de.teamlapen.vampirism.player.ModPlayerEventHandler.onTryMount(ModPlayerEventHandler.java:161) ~[vampirism:1.8.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_262_ModPlayerEventHandler_onTryMount_EntityMountEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.canMountEntity(ForgeEventFactory.java:456) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_184205_a(Entity.java:1656) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_184205_a(MobEntity.java:1241) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_184220_m(Entity.java:1641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.ZombieEntity.func_213386_a(ZombieEntity.java:433) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:175) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.teamlapen.vampirism.player.ModPlayerEventHandler.onTryMount(ModPlayerEventHandler.java:161) ~[vampirism:1.8.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_262_ModPlayerEventHandler_onTryMount_EntityMountEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.canMountEntity(ForgeEventFactory.java:456) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_184205_a(Entity.java:1656) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_184205_a(MobEntity.java:1241) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_184220_m(Entity.java:1641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.ZombieEntity.func_213386_a(ZombieEntity.java:433) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:175) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['joan7'/1051, l='ServerLevel[New World]', x=-1306.41, y=64.00, z=-1841.14]]
	Chunk stats: ServerChunkCache: 4188
	Level dimension: minecraft:overworld
	Level spawn location: World: (-264,66,74), Chunk: (at 8,4,10 in -17,4; contains blocks -272,0,64 to -257,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 402843275 game time, 180209078 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 98203 (now: false), thunder time: 3831 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-91-generic
	Java Version: 16.0.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 7703840816 bytes (7346 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx10G -Xms10G
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.22.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.1.0.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.22
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.22-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.1.90.jar             |Useful Backpacks              |usefulbackpacks               |1.12.1.90           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		mining_helmet-1.16.5-2.0.1.jar                    |Mining Helmet                 |mining_helmet                 |2.0.1               |DONE      |Manifest: NOSIGNATURE
		quiver-2.2-1.16.5.jar                             |Quiver                        |quiver                        |2.2-1.16.5          |DONE      |Manifest: NOSIGNATURE
		SimpleCoreLib-1.16.5-2.0.8.22.jar                 |SimpleCoreLib                 |simplecorelib                 |1.16.5-2.0.8.22     |DONE      |Manifest: NOSIGNATURE
		ineedthemores-1.16.4-1.3.jar                      |I Need Them Ores              |ineedthemores                 |1.16.4-1.3          |DONE      |Manifest: NOSIGNATURE
		refinedpipes-0.5.1.jar                            |Refined Pipes                 |refinedpipes                  |0.5.1               |DONE      |Manifest: NOSIGNATURE
		forbidden_arcanus-1.16.4-1.0.0.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.16.4-1.0.0        |DONE      |Manifest: NOSIGNATURE
		extrabows-v1.16.4+b3.jar                          |Extra Bows                    |extrabows                     |v1.16.4 b3          |DONE      |Manifest: NOSIGNATURE
		Craftable+Saddles+[1.16+All]-1.3.jar              |Craftable Saddles             |craftable_saddles             |1.3                 |DONE      |Manifest: NOSIGNATURE
		Pillagers-1.16.5-3.0.1.jar                        |Pillagers                     |pillagers                     |3.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Guide-API-VP-1.16.5-2.2.2.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.2               |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.3.jar                        |Waystones                     |waystones                     |7.6.3               |DONE      |Manifest: NOSIGNATURE
		WeaponThrow-1.16.4-5.4.jar                        |Weapon Throw                  |weaponthrow                   |1.16.4-5.4          |DONE      |Manifest: NOSIGNATURE
		OresAboveDiamonds-1.16.5-v6.4.1.jar               |Ores Above Diamonds           |oresabovediamonds             |6.4.1               |DONE      |Manifest: NOSIGNATURE
		StrongerSnowballs-1.16.5-5.0.1.jar                |StrongerSnowballs             |strongersnowballs             |5.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		potionofbees-1.16.4-1.1.0.2.jar                   |Potion of Bees                |potionofbees                  |1.1.0.2             |DONE      |Manifest: NOSIGNATURE
		MagicDoorknob-1.16.5-0.1.4.465.jar                |Magic Doorknob                |magic_doorknob                |1.16.5-0.1.4.465    |DONE      |Manifest: NOSIGNATURE
		u_team_core-1.16.5-3.2.1.196.jar                  |U Team Core                   |uteamcore                     |3.2.1.196           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		mahoutsukai-1.16.5-v1.32.1.jar                    |Mahou Tsukai                  |mahoutsukai                   |1.16.5-v1.32.1      |DONE      |Manifest: NOSIGNATURE
		Fusion-1.16.5-2.7.4.4.jar                         |SimpleOres:Fusion             |fusion                        |1.16.5-2.7.4.4      |DONE      |Manifest: NOSIGNATURE
		gunswithoutroses-1.16.5-1.0.9.jar                 |Guns Without Roses            |gunswithoutroses              |1.0.9               |DONE      |Manifest: NOSIGNATURE
		VampiresNeedUmbrellas-1.16.5-1.1.3.jar            |Vampires Need Umbrellas       |vampiresneedumbrellas         |1.1.3               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.8.5.jar                        |Vampirism                     |vampirism                     |1.8.5               |DONE      |Manifest: NOSIGNATURE
		Werewolves-1.16.5-1.8-0.5.6.jar                   |Werewolves                    |werewolves                    |0.5.6-alpha+20210922|DONE      |Manifest: NOSIGNATURE
		BetterThanMending-1.6.0.jar                       |BetterThanMending             |betterthanmending             |1.6.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-universal.jar                |Forge                         |forge                         |36.2.22             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |DONE      |Manifest: NOSIGNATURE
		SimpleOres2-1.16.5-2.4.7.2.jar                    |Simple Ores                   |simpleores                    |1.16.5-2.4.7.2      |DONE      |Manifest: NOSIGNATURE
		bigbuckets-1.1.5.jar                              |BigBuckets                    |bigbuckets                    |1.1.5               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: c3a62ee6-86e7-4c60-984e-388436afd527
	Player Count: 1 / 20; [ServerPlayerEntity['joan7'/1051, l='ServerLevel[New World]', x=-1306.41, y=64.00, z=-1841.14]]
	Data Packs: vanilla, mod:usefulbackpacks, mod:mining_helmet (incompatible), mod:quiver (incompatible), mod:simplecorelib, mod:ineedthemores (incompatible), mod:forbidden_arcanus (incompatible), mod:extrabows (incompatible), mod:craftable_saddles (incompatible), mod:pillagers, mod:curios, mod:waystones (incompatible), mod:weaponthrow, mod:oresabovediamonds (incompatible), mod:strongersnowballs, mod:potionofbees (incompatible), mod:magic_doorknob (incompatible), mod:uteamcore, mod:vampirism, mod:mahoutsukai (incompatible), mod:fusion, mod:gunswithoutroses (incompatible), mod:betterthanmending, mod:forge, mod:overloadedarmorbar (incompatible), mod:bigbuckets (incompatible), mod:guideapi-vp, mod:werewolves, mod:refinedpipes, mod:vampiresneedumbrellas (incompatible), mod:simpleores
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by maxanier** [comment]
Thank you for reporting. I messed up there. I should really stop modding after 9h of work.

Will be fixed tonight.
