### ISSUE TITLE
[Bug]: Game crashes when Vampire Hunters shoot a crossbow

### ISSUE THREAD

**Issue by merviria** [TeamLapen/Vampirism#1146]
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.16.5

### Singleplayer/Multiplayer

Both

### What happened?

While playing either a multiplayer or singleplayer, when Vampire Hunters shoot a crossbow, there's a random chance of the game crashing. I didn't notice how that happened in the multiplayer as I wasn't close to the hunters, but a few seconds later of trying to get away it crashed. I loaded a creative world and spawned a hunter to shoot me and I crashed as soon as I died.

### Relevant log output

```shell
[20:09:10] [main/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 11/3/22 8:09 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.item.AirItem cannot be cast to de.teamlapen.vampirism.api.items.IVampirismCrossbow
	at de.teamlapen.vampirism.entity.goals.AttackRangedCrossbowGoal.func_75246_d(AttackRangedCrossbowGoal.java:124) ~[?:1.9.0-alpha+20220826-2128] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at de.teamlapen.vampirism.entity.VampirismEntity.func_70636_d(VampirismEntity.java:110) ~[?:1.9.0-alpha+20220826-2128] {re:classloading}
	at de.teamlapen.vampirism.entity.hunter.BasicHunterEntity.func_70636_d(BasicHunterEntity.java:149) ~[?:1.9.0-alpha+20220826-2128] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at de.teamlapen.vampirism.entity.VampirismEntity.func_70071_h_(VampirismEntity.java:180) ~[?:1.9.0-alpha+20220826-2128] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$10044/2146289428.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$9688/1955987307.run(Unknown Source) ~[?:?] {}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.teamlapen.vampirism.entity.goals.AttackRangedCrossbowGoal.func_75246_d(AttackRangedCrossbowGoal.java:124) ~[?:1.9.0-alpha+20220826-2128] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at de.teamlapen.vampirism.entity.VampirismEntity.func_70636_d(VampirismEntity.java:110) ~[?:1.9.0-alpha+20220826-2128] {re:classloading}
	at de.teamlapen.vampirism.entity.hunter.BasicHunterEntity.func_70636_d(BasicHunterEntity.java:149) ~[?:1.9.0-alpha+20220826-2128] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:vampirism.mixins.json:MixinMobEntity,pl:mixin:A}
	at de.teamlapen.vampirism.entity.VampirismEntity.func_70071_h_(VampirismEntity.java:180) ~[?:1.9.0-alpha+20220826-2128] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$10044/2146289428.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: vampirism:hunter_imob (de.teamlapen.vampirism.entity.hunter.BasicHunterEntity.IMob)
	Entity ID: 1038
	Entity Name: Vampire Hunter
	Entity's Exact location: -546.35, 64.64, -792.29
	Entity's Block location: World: (-547,64,-793), Chunk: (at 13,4,7 in -35,-50; contains blocks -560,0,-800 to -545,255,-785), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Entity's Momentum: 0.02, 0.19, 0.20
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Aqualin'/620, l='ServerLevel[halloween smp with angie]', x=-644.06, y=86.01, z=-802.16]]
	Chunk stats: ServerChunkCache: 4880
	Level dimension: minecraft:overworld
	Level spawn location: World: (-204,63,79), Chunk: (at 4,3,15 in -13,4; contains blocks -208,0,64 to -193,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1377149 game time, 903006 day time
	Level name: halloween smp with angie
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 130506 (now: false), thunder time: 66509 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$9688/1955987307.run(Unknown Source) ~[?:?] {}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3161683816 bytes (3015 MB) / 5234491392 bytes (4992 MB) up to 7348420608 bytes (7008 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx7000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.1.103.jar            |Useful Backpacks              |usefulbackpacks               |1.12.1.103          |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		majobroom1.3.1.jar                                |Majo Broom Mod                |majobroom                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.16.5-5.7.jar                      |Tree Harvester                |treeharvester                 |5.7                 |DONE      |Manifest: NOSIGNATURE
		fairylights-4.0.5-1.16.5.jar                      |Fairy Lights                  |fairylights                   |4.0.5               |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.1.jar                   |Abnormals Core                |abnormals_core                |3.3.1               |DONE      |Manifest: NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |DONE      |Manifest: NOSIGNATURE
		Guide-API-VP-1.16.5-2.2.2.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.2               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-5.13.jar                        |Collective                    |collective                    |5.13                |DONE      |Manifest: NOSIGNATURE
		MorePlayerModels-1.16.5.20220731.jar              |More Player Models            |moreplayermodels              |1.16.5.20220731     |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p5.jar                     |Journeymap                    |journeymap                    |5.8.5p5             |DONE      |Manifest: NOSIGNATURE
		autumnity-1.16.5-2.1.2.jar                        |Autumnity                     |autumnity                     |2.1.2               |DONE      |Manifest: NOSIGNATURE
		u_team_core-1.16.5-3.2.1.229.jar                  |U Team Core                   |uteamcore                     |3.2.1.229           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		ravencoffee-1.16.5-alpha_rev2.jar                 |Raven Coffee Mod              |ravencoffee                   |1.16.3-0.1          |DONE      |Manifest: NOSIGNATURE
		basic_discord_rich_presence-1.16.5-1.0.0.10.jar   |Basic Discord Rich Presence   |basicdiscordrichpresence      |1.0.0.10            |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		A+Sweet+Tooth's+Fantacy+-+Forge+1.16.5.jar        |A SweetTooth's Fantasy        |sweettooth_fantasy            |1.0                 |DONE      |Manifest: NOSIGNATURE
		mystical_pumpkins-0.3.1.jar                       |Mystical Pumpkins             |mystical_pumpkins             |0.3.1               |DONE      |Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.22.jar                      |Carry On                      |carryon                       |1.15.5.22           |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		registrator-1.16.5-1.4.2.jar                      |Registrator                   |registrator                   |1.4.2               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.4.0.jar                |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.9.0-alpha+20220826-2128.jar    |Vampirism                     |vampirism                     |1.9.0-alpha+20220826|DONE      |Manifest: NOSIGNATURE
		apexcore-1.16.5-1.9.4.jar                         |ApexCore                      |apexcore                      |1.9.4               |DONE      |Manifest: NOSIGNATURE
		fantasyfurniture-1.16.5-2.0.2.jar                 |Fantasy's Furniture           |fantasyfurniture              |2.0.2               |DONE      |Manifest: NOSIGNATURE
		VampiresNeedUmbrellas-1.16.5-1.1.5.jar            |Vampires Need Umbrellas       |vampiresneedumbrellas         |1.1.5               |DONE      |Manifest: NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.17.jar                |TLSkinCape                    |tlskincape                    |1.17                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		geckolib-forge-1.16.5-3.0.90.jar                  |GeckoLib                      |geckolib3                     |3.0.90              |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.25.7.jar                     |Ars Nouveau                   |ars_nouveau                   |1.25.7              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b8e4dc75-680d-44b3-a478-c9fec6d7dffd
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['Aqualin'/620, l='ServerLevel[halloween smp with angie]', x=-644.06, y=86.01, z=-802.16]]
	Data Packs: vanilla, mod:jei, mod:fairylights, mod:abnormals_core, mod:guideapi-vp, mod:curios, mod:collective, mod:moreplayermodels, mod:journeymap (incompatible), mod:autumnity, mod:ravencoffee, mod:vampirism, mod:mystical_pumpkins, mod:carryon, mod:vampiresneedumbrellas (incompatible), mod:forge, mod:appleskin, mod:tlskincape (incompatible), mod:geckolib3 (incompatible), mod:torohealth, mod:usefulbackpacks, mod:uteamcore, mod:basicdiscordrichpresence, mod:sweettooth_fantasy, mod:registrator, mod:apexcore, mod:fantasyfurniture, mod:majobroom, mod:patchouli (incompatible), mod:ars_nouveau, mod:treeharvester
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_v4.6.zip
	OpenGlVersion: 4.6.0 NVIDIA 512.15
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

### Reproduce steps

Get a Vampire Hunter to shoot a crossbow (random chance of crashing, whether you died or not)

### Other relevant mods

Mods are listed in the crash report.

**Comment by Cheaterpaul** [comment]
update your vampirism version. This is already fixed
