### ISSUE TITLE
[Bug]: server crashes at startup

### ISSUE THREAD

**Issue by WEEDMEN** [TeamLapen/Vampirism#1178]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Vampirism Version

1.9.1

### Singleplayer/Multiplayer

Multiplayer

### What happened?

server crashes at startup
incompatibility with cooking for blockheads, a link for you to understand the error https://github.com/TwelveIterationMods/CookingForBlockheads/issues/547#issuecomment-980432284

### Relevant log output

```shell
Caused by: java.lang.NoClassDefFoundError: net/blay09/mods/cookingforblockheads/IMCHandler
	at net.minecraftforge.eventbus.ASMEventHandler_267_IMCHandler_onFoodRegistryInit_FoodRegistryInitEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[mohist.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:284) ~[mohist.jar:?]
	at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.initFoodRegistry(CookingRegistry.java:56) ~[cookingforblockheads:9.3.4]
	at net.blay09.mods.cookingforblockheads.CookingForBlockheads.lambda$addReloadListenersLate$2(CookingForBlockheads.java:133) ~[cookingforblockheads:9.3.4]
	at net.minecraft.resources.IResourceManagerReloadListener.func_232635_a_(IResourceManagerReloadListener.java:18) ~[?:?]
```

### Reproduce steps

1. Load server world

### Other relevant mods

CookingForBlockheads 9.3.4

**Comment by Cheaterpaul** [comment]
Has this anything to do with Vampirism?

**Comment by BlayTheNinth** [comment]
https://github.com/TeamLapen/Vampirism/blob/1.19/src/main/java/de/teamlapen/vampirism/config/BloodValues.java#L30

Using `thenAcceptAsync` breaks class loading of reload listeners running after yours, as it uses a default executor that was created with a different parent class loader than the one Forge uses for mods.

You need to either use `thenAccept` or supply your own `Executor` as second argument to `thenAcceptAsync`.
