### ISSUE TITLE
[Bug]: Crash on render signs

### ISSUE THREAD

**Issue by YoshiNoodles** [TeamLapen/Vampirism#1196]
### Minecraft Version

1.16.x

### Forge Version

36.2.34

### Vampirism Version

1.9.3

### Singleplayer/Multiplayer

Both

### What happened?

I'm playing on a friend's self-made modpack, and we've had some issues with Tinkers Construct signs rendering properly -- sometimes they show missing textures.  There's a simple solve: just completely close and reload the modpack.  Problem is, that takes time, and so to mitigate that, I went to replace some of our Tinkers signs with Cursed signs, and the moment I placed one, it crashed the game with the attached message.  Thinking it was just that particular type of sign, I tried the Dark Spruce sign in a singleplayer world, and got the same crash.  I don't know if it's something with the Vampirism mod or another mod in our pack (either on the server or client-side).

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/5/23 9:54 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at net.minecraft.client.renderer.tileentity.SignTileEntityRenderer.func_225616_a_(SignTileEntityRenderer.java:69) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.SignTileEntityRenderer.func_225616_a_(SignTileEntityRenderer.java:30) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:128) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$24913/1680131621.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:174) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1816) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.setSectionDirty,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:mixin:A}
	at com.swdteam.util.RenderUtil.renderLevel(RenderUtil.java:45) ~[?:67.0.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.redirect$zbk000$renderLevel(GameRenderer.java:2003) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.dalekmod.json:GameRendererMixin,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.dalekmod.json:GameRendererMixin,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.dalekmod.json:GameRendererMixin,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dalekmod.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dalekmod.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$466/222179461.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.tileentity.SignTileEntityRenderer.func_225616_a_(SignTileEntityRenderer.java:69) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.SignTileEntityRenderer.func_225616_a_(SignTileEntityRenderer.java:30) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:128) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$24913/1680131621.run(Unknown Source) ~[?:?] {}
-- Block Entity Details --
Details:
	Name: minecraft:sign // net.minecraft.tileentity.SignTileEntity
	Block: Block{vampirism:dark_spruce_sign}[rotation=8,waterlogged=false]
	Block location: World: (-260,65,-317), Chunk: (at 12,4,3 in -17,-20; contains blocks -272,0,-320 to -257,255,-305), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{vampirism:dark_spruce_sign}[rotation=8,waterlogged=false]
	Block location: World: (-260,65,-317), Chunk: (at 12,4,3 in -17,-20; contains blocks -272,0,-320 to -257,255,-305), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:174) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1816) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.setSectionDirty,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:twilightforest:render,xf:fml:journeymap:WorldRenderer.setSectionDirty,pl:mixin:A}
	at com.swdteam.util.RenderUtil.renderLevel(RenderUtil.java:45) ~[?:67.0.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.redirect$zbk000$renderLevel(GameRenderer.java:2003) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.dalekmod.json:GameRendererMixin,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:cgm.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.dalekmod.json:GameRendererMixin,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:A}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['YoshiNoodles'/2053, l='ClientLevel', x=-259.74, y=65.28, z=-317.58]]
	Chunk stats: Client Chunk Cache: 169, 64
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,71,-80), Chunk: (at 0,4,0 in -14,-5; contains blocks -224,0,-80 to -209,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 26074 game time, 26074 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dalekmod.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.dalekmod.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$466/222179461.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 735915112 bytes (701 MB) / 5057806336 bytes (4823 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 4
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.17.0
	Mod List: 
		supermartijn642configlib-1.1.6-forge-mc1.16.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |DONE      |Manifest: NOSIGNATURE
		cgm-1.2.6-1.16.5.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.6               |DONE      |Manifest: NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.153.jar                          |Just Enough Items             |jei                           |7.7.1.153           |DONE      |Manifest: NOSIGNATURE
		constructsarmory-forge-2.0.0-alpha.2+1.16.5.jar   |Construct's Armory            |constructsarmory              |2.0.0-alpha.2+1.16.5|DONE      |Manifest: NOSIGNATURE
		MoGuns-1.8.3-1.16.5.jar                           |Mo' Guns                      |moguns                        |1.8.3               |DONE      |Manifest: NOSIGNATURE
		Guide-API-VP-1.16.5-2.2.2.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.2               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p6.jar                     |Journeymap                    |journeymap                    |5.8.5p6             |DONE      |Manifest: NOSIGNATURE
		Decoration Mod 1.6 (Ver 1.16.5).jar               |Decoration and furniture mod  |decoration_mod                |1.6.0               |DONE      |Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.16.5-1.5.3.jar             |Simple Storage Network        |storagenetwork                |1.16.5-1.5.3        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		additional-guns-0.8.0-1.16.5.jar                  |Additional Guns               |additionalguns                |0.8.0               |DONE      |Manifest: NOSIGNATURE
		SCPOvertime-1.16.5-1.5.2.1.jar                    |SCP: Overtime                 |ascpm                         |1.5.2               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.15.20.755.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.15.20.755  |DONE      |Manifest: NOSIGNATURE
		buildinggadgets-1.16.5-3.8.3-build.20+mc1.16.5.jar|Building Gadgets              |buildinggadgets               |3.8.3-build.20+mc1.1|DONE      |Manifest: NOSIGNATURE
		RoundelMod Release 9.1.jar                        |Timesplit Roundel Mod         |trm                           |Alpha Release 9.0   |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.7.0.jar                       |iChunUtil                     |ichunutil                     |10.7.0              |DONE      |Manifest: NOSIGNATURE
		Tardis-Mod-1.16.5-1.5.4.jar                       |Tardis Mod                    |tardis                        |1.5.4               |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		xercamusic-1.16.5-2.1.1.jar                       |Xerca's Music Maker Mod       |xercamusic                    |1.16.5-2.1.1        |DONE      |Manifest: NOSIGNATURE
		Morph-1.16.5-10.2.1.jar                           |Morph                         |morph                         |10.2.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.3.4.335.jar                   |Tinkers' Construct            |tconstruct                    |3.3.4.335           |DONE      |Manifest: NOSIGNATURE
		lucky-block-forge-1.16.5-5.0.jar                  |Lucky Block                   |lucky                         |1.16.5-1            |DONE      |Manifest: NOSIGNATURE
		torchmaster-2.3.8.jar                             |Torchmaster                   |torchmaster                   |2.3.8               |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.16.5forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.6-forge-mc1.16.jar     |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.6               |DONE      |Manifest: NOSIGNATURE
		movingelevators-1.3.11a-forge-mc1.16.jar          |Moving Elevators              |movingelevators               |1.3.11a             |DONE      |Manifest: NOSIGNATURE
		dalekmod-67.0.0.jar                               |Dalek Mod                     |dalekmod                      |67.0.0              |DONE      |Manifest: NOSIGNATURE
		tardis_consoles-colorized_0.9.1_B.jar             |Tardis Consoles: Colorized    |tcc                           |1.16.5-1.0 RELEASE  |DONE      |Manifest: NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.4.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.1.0.0.jar                   |Curios API                    |curios                        |1.16.5-4.1.0.0      |DONE      |Manifest: NOSIGNATURE
		temporal_additions-1.16.5-0.2.1.jar               |Temporal Additions            |tadditions                    |0.2.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Mantle-1.16.5-1.6.157.jar                         |Mantle                        |mantle                        |1.6.157             |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |Manifest: NOSIGNATURE
		baubleyheartcanisters-1.16.5-1.1.11.jar           |Baubley Heart Canisters       |bhc                           |1.16.5-1.1.11       |DONE      |Manifest: NOSIGNATURE
		[1.16.5] SecurityCraft v1.9.6.1.jar               |SecurityCraft                 |securitycraft                 |v1.9.6.1            |DONE      |Manifest: NOSIGNATURE
		angelring-1.16.5-2.0.2.jar                        |Angel Ring 2                  |angelring                     |2.0.2               |DONE      |Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |DONE      |Manifest: NOSIGNATURE
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |DONE      |Manifest: NOSIGNATURE
		notenoughtardis-2.0+-+1.16+Update.jar             |Not Enough TARDIS             |notenoughtardis               |2.0 - 1.16 Update   |DONE      |Manifest: NOSIGNATURE
		SpartanWeaponry-1.16.5-2.2.0-rc-2.jar             |Spartan Weaponry              |spartanweaponry               |2.2.0 Release Candid|DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |DONE      |Manifest: NOSIGNATURE
		morecfm-1.3.1-1.16.3.jar                          |MrCrayfish's More Furniture Mo|morecfm                       |1.3.1               |DONE      |Manifest: NOSIGNATURE
		nfm-2022.10.27-1.16.5.jar                         |Nosiphus Furniture Mod        |nfm                           |2022.10.27          |DONE      |Manifest: NOSIGNATURE
		architectury-1.32.66.jar                          |Architectury                  |architectury                  |1.32.66             |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.9.3.jar                        |Vampirism                     |vampirism                     |1.9.3               |DONE      |Manifest: NOSIGNATURE
		Werewolves-1.16.5-1.1.0.1.jar                     |Werewolves                    |werewolves                    |1.1.0.1             |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		mcw-furniture-3.1.0-mc1.16.5forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.1.0               |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.16.91-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.16.91             |DONE      |Manifest: NOSIGNATURE
		wings-2.1.0-1.16.5.jar                            |Wings                         |wings                         |2.1.0               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
		DivineRPG-1.8.27.jar                              |DivineRPG                     |divinerpg                     |1.8.27              |DONE      |Manifest: NOSIGNATURE
		GoodOlCurrency-Beta-0.0.1.jar                     |Good Ol' Currency             |gocurrency                    |Beta-0.0.1          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: cb490d0c-2daf-46d3-8400-06ceedce319b
	Launched Version: forge-36.2.34
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon(TM) RX 460 Graphics GL version 4.6.0 Compatibility Profile Context 23.3.1.230305, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 23.3.1.230305
	OpenGlRenderer: Radeon(TM) RX 460 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```

### Reproduce steps

1. Load into world -- can be server or singleplayer, doesn't matter
2. Craft Cursed or Dark Spruce Sign or grab from JEI/creative menu
3. Place sign
4. Profit

### Other relevant mods

Our mod list is as follows:
Additional Guns 0.8.0
Angel Ring 2.0.2
Baubley Heart Canisters 1.1.11
Building Gadgets 3.8.3-build.20
Construct's Armory 2.0.0
Create 0.3.2g
Curios API 4.1.0.0
Dalek Mod 67.0.0
Decoration and Furniture Mod 1.6
DivineRPG 1.8.27
FerriteCore 2.1.1
Good Ol' Currency Beta 0.0.1
Guide-API Village and Pillage 2.2.2
Hwyla 1.10.11-B78
JourneyMap 5.8.5p6
JEI 7.7.1.153
Macaw's Fences and Walls 1.0.7
Macaw's Furniture 3.1.0
Moving Elevators 1.3.11a
Mo' Guns 1.8.3
Morph 10.2.1
MrCrayfish's Furniture Mod 7.0.0pre22
MrCrayfish's Gun Mod 1.2.6
MrCrayfish's More Furniture Mod 1.3.1
MrCrayfish's Vehicle Mod 0.45.2
Xerca's Music Maker Mod 2.1.1
New TARDIS Mod 1.5.4
Nosiphus Furniture Mod 2022.10.27
NotEnoughTARDIS 2.0
Pam's HarvestCraft 2 -- Food Core and Food Extended
Roundel Mod Release 9.1
SCP: Overtime 1.5.2.1
SecurityCraft 1.9.6.1
Simple Storage Network 1.5.3
Sophisticated Backpacks 3.15.20.755
Spartan Weaponry 2.2.0-rc-2
Tardis Consoles: Colorized 0.9.1 Beta
Temporal Additions 0.2.1
Twilight Forest 4.0.870
Tinkers Construct 3.3.4.335
Torchmaster 2.3.8
Vampirism 1.9.3
Werewolves 1.1.0.1
Wings 2.1.0
Wyrmroost 1.2.11

**Comment by YoshiNoodles** [comment]
I will add that I use Optifine and MouseTweaks client-side as well, if that has any bearing on the issue.

**Comment by maxanier** [comment]
So far I was unable to reproduce this with just Vampirism and Optifine.
Does this only happen with Vampirism signs, or also with vanilla wooden signes?

**Comment by YoshiNoodles** [comment]
Just Vampirism signs

**Comment by YoshiNoodles** [comment]
Might it be a compatibility issue with one of our other mods?

**Comment by Cheaterpaul** [comment]
Moving Elevator seemingly does some early loading of the texture atlases. I do not know why it crashes, but with the fixes it will work.

**Comment by maxanier** [comment]
If this is urgent, you can grab a fixed version here: https://cloud.maxgb.de/s/JiBfKD4ACHHTcky
Otherwise you can wait for the next release on curse

**Comment by YoshiNoodles** [comment]
Thanks so much for looking into this, I really appreciate it.
