### ISSUE TITLE
Crashes because FML cannot initialize class de.teamlapen.vampirism.VampirismMod

### ISSUE THREAD

**Issue by NuclearFart** [TeamLapen/Vampirism#123]
Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.69-ex110.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 02/10/16 14:11
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class de.teamlapen.vampirism.VampirismMod
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:576)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class de.teamlapen.vampirism.VampirismMod
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:50)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:575)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 150953096 bytes (143 MB) / 416972800 bytes (397 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2094 Optifine OptiFine_1.10.2_HD_U_C3 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2094.jar) 
	UC	Forge{12.18.1.2094} [Minecraft Forge] (forge-1.10.2-12.18.1.2094.jar) 
	UC	movillages{1.5.2} [Mo' Villages] ([1.9.4]Mo' Villages-1.5.2.jar) 
	UC	SmithsCore{1.10.2-1.2.0.0-251} [Smiths Core] (smithscore-1.10.2-1.2.0.0-251.jar) 
	UC	Armory{1.10.2-1.2.0.0-338} [Armory] (armory-1.10.2-1.2.0.0-338.jar) 
	UC	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UC	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UC	armory-weaponry{@VERSION@} [armory-weaponry] (Armory-Weaponry-1.3.0-53.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	SonarCore{3.1.6} [SonarCore] (SonarCore-1.9.4-3.1.6.jar) 
	UC	Calculator{3.1.2} [Calculator] (Calculator-1.9.4-3.1.2.jar) 
	UC	IC2{2.6.69-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.69-ex110.jar) 
	UC	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UC	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UE	vampirism{1.0.1} [Vampirism] (Vampirism-1.10.2-1.0.1-deobf.jar) 
	UE	teamlapen-lib{1.0.1} [TeamLapen Library] (Vampirism-1.10.2-1.0.1-deobf.jar) 
	UC	mcmultipart{1.2.0_74} [MCMultiPart] (MCMultiPart-experimental-1.2.0_74-universal.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.69-ex110.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.12002 Compatibility Profile Context 9.12.6.1000' Renderer: 'AMD Radeon HD 7340 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.10.2_HD_U_C3
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.2.12002 Compatibility Profile Context 9.12.6.1000
	OpenGlRenderer: AMD Radeon HD 7340 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by maxanier** [comment]
Looks like you downloaded the "-deobf" version of Vampirism, that can only be used in a development environment.
Please download the normal version here https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2331646/download
