### ISSUE TITLE
[Bug]: Invalid player data  Couldn't place player in world

### ISSUE THREAD

**Issue by Klosw** [TeamLapen/Vampirism#1237]
### Minecraft Version

1.20.1

### Forge Version

47.0.19

### Vampirism Version

1.9.1-alpha+20230621-1954

### Modpack

https://drive.google.com/file/d/1E-xWqDWXjqQYQjAdBN3CdTluUfqXolRW/view?usp=drive_link

### Singleplayer/Multiplayer

Server

### What happened?

Exit after one game and cannot enter the game again 

### Relevant log output

```shell
https://drive.google.com/file/d/1ksNddrY3FzlT9-7yA_7smMHUIRvSXDwg/view?usp=drive_link


[12:15:27] [Server thread/INFO] [minecraft/DedicatedServer]: Done (9.771s)! For help, type "help"
[12:15:27] [Server thread/INFO] [ne.mi.se.pe.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
[12:16:49] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
net.minecraft.ReportedException: Loading entity NBT
        at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1762) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:MixinEntity,pl:mixin:A}
        at net.minecraft.world.level.storage.PlayerDataStorage.m_78435_(PlayerDataStorage.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading}
        at net.minecraft.server.players.PlayerList.m_11224_(PlayerList.java:324) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo}
        at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:157) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:909) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:816) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:663) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.m_9829_(net.minecraft.network.protocol.Packet)" because "p_12803_.f_8906_" is null
        at net.minecraft.stats.ServerRecipeBook.m_12801_(ServerRecipeBook.java:70) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading}
        at net.minecraft.stats.ServerRecipeBook.m_12791_(ServerRecipeBook.java:47) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading}
        at net.minecraft.server.level.ServerPlayer.m_7281_(ServerPlayer.java:1052) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerPlayer.m_7902_(ServerPlayer.java:1066) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.advancements.AdvancementRewards.m_9989_(AdvancementRewards.java:69) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading}
        at net.minecraft.server.PlayerAdvancements.m_135988_(PlayerAdvancements.java:181) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:mixin,re:classloading,pl:mixin:APP:vampirism.mixins.json:PlayerAdvancementsAccessor,pl:mixin:A}
        at net.minecraft.advancements.CriterionTrigger$Listener.m_13686_(CriterionTrigger.java:35) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading}
        at net.minecraft.advancements.critereon.SimpleCriterionTrigger.m_66234_(SimpleCriterionTrigger.java:74) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:classloading}
        at de.teamlapen.vampirism.advancements.critereon.SkillUnlockedCriterionTrigger.trigger(SkillUnlockedCriterionTrigger.java:31) ~[Vampirism-1.20.1-1.9.1-alpha+20230621-1954.jar%23117!/:1.9.1-alpha+20230621-1954] {re:classloading}
        at de.teamlapen.vampirism.entity.player.skills.SkillHandler.enableSkill(SkillHandler.java:173) ~[Vampirism-1.20.1-1.9.1-alpha+20230621-1954.jar%23117!/:1.9.1-alpha+20230621-1954] {re:classloading}
        at de.teamlapen.vampirism.entity.player.skills.SkillHandler.loadFromNbt(SkillHandler.java:298) ~[Vampirism-1.20.1-1.9.1-alpha+20230621-1954.jar%23117!/:1.9.1-alpha+20230621-1954] {re:classloading}
        at de.teamlapen.vampirism.entity.player.hunter.HunterPlayer.loadData(HunterPlayer.java:189) ~[Vampirism-1.20.1-1.9.1-alpha+20230621-1954.jar%23117!/:1.9.1-alpha+20230621-1954] {re:classloading}
        at de.teamlapen.vampirism.entity.player.hunter.HunterPlayer$2.deserializeNBT(HunterPlayer.java:91) ~[Vampirism-1.20.1-1.9.1-alpha+20230621-1954.jar%23117!/:1.9.1-alpha+20230621-1954] {re:classloading}
        at de.teamlapen.vampirism.entity.player.hunter.HunterPlayer$2.deserializeNBT(HunterPlayer.java:84) ~[Vampirism-1.20.1-1.9.1-alpha+20230621-1954.jar%23117!/:1.9.1-alpha+20230621-1954] {re:classloading}
        at net.minecraftforge.common.capabilities.CapabilityDispatcher.deserializeNBT(CapabilityDispatcher.java:127) ~[forge-1.20.1-47.0.19-universal.jar%23126!/:?] {re:classloading}
        at net.minecraftforge.common.capabilities.CapabilityProvider.deserializeCaps(CapabilityProvider.java:148) ~[forge-1.20.1-47.0.19-universal.jar%23126!/:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1736) ~[server-1.20.1-20230612.114412-srg.jar%23121!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vampirism.mixins.json:MixinEntity,pl:mixin:A}
        ... 14 more
[12:16:49] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@4fb2540d[id=cadab87b-d467-3141-aca8-2c8612aac187,name=KLOSW,properties={},legacy=false] (/127.0.0.1:57438) lost connection: Invalid player data
[12:16:49] [Server thread/WARN] [minecraft/Connection]: handleDisconnection() called twice
```

### Reproduce steps

Use the mods above to generate the world (server) and use the provided player file (server) in world/playerdata. The client uses the offline user username KLOSW for gaming

使用上面mods生成世界（服务器） 并且在world/playerdata 使用上面提供的 player的文件（服务器） ，客户端使用离线用户用户名为 KLOSW 进行游戏 

![image](https://github.com/TeamLapen/Vampirism/assets/13143959/871201cf-d9c3-4c80-b0c7-a31fef3d7f4c)

**Comment by Cheaterpaul** [comment]
This is most likely caused by your client not being correctly connected to the server.

But you can try this again once the new version is published

**Comment by Klosw** [comment]
> 这很可能是由于您的客户端未正确连接到服务器造成的。
> 
> 但新版本发布后您可以再次尝试
换个角色就能进入 ,就这个不行

**Comment by Klosw** [comment]
> This is most likely caused by your client not being correctly connected to the server.
> 
> But you can try this again once the new version is published

The bug has been fixed
