### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by parke2r** [TeamLapen/Vampirism#124]
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_101]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_101]
        at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:586) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:343) ~[sf.class:?]
        at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208) ~[sg.class:?]
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359) ~[rw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1938) ~[sf.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[sg.class:?]
        **at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:175) ~[EntityVampirism.class:?]**
        at net.minecraft.world.World.func_72866_a(World.java:1964) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838) ~[ls.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1934) ~[aid.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1750) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
        ... 4 more

Seems to happen when I'm chopping away at vampirism mobs e.g. captain or the powerful bill
Running on RHEL7 x86_64.
Let me know if you need any more info ....

**Comment by parke2r** [comment]
using : Vampirism-1.10.2-1.0.1.jar

**Comment by maxanier** [comment]
Ok, sorry for letting you wait so long, but I did not work on Vampirism lately.

I took a look at it, but could not find the problem. Since I've not heard any other reports so far I think it might have to do with other mods.
Maybe you can upload your full server log (to pastebin or so).

Does this occur everytime you kill a Advanced Vampire or only sometimes and does it only happen with advanced vampires or also with normal vampires or even hunters?
Thank You

**Comment by parke2r** [comment]
Hey, no worries.

I think you can probably close this one.  I updated some of the other mods I'm using and the problem has gone away so I suspect your diagnosis was spot on.

Thanks.
