### ISSUE TITLE
[Bug]: Cannot get Vampire Player capabilities

### ISSUE THREAD

**Issue by Reaviik** [TeamLapen/Vampirism#1332]
### Minecraft Version

1.20.x

### Forge Version

47.2.6

### Vampirism Version

1.10.5

### Modpack

https://www.curseforge.com/minecraft/modpacks/infinity-nexus-unnamed

### Singleplayer/Multiplayer

Server

### What happened?

This server is running Arclight version arclight-1.20.1-1.0.2-730181a4 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Relevant log output

```shell
[17:11:26 WARN] [d.t.v.e.p.v.VampirePlayer]: Cannot get Vampire player capability. This might break mod functionality.
java.lang.Throwable: null
        at de.teamlapen.vampirism.entity.player.vampire.VampirePlayer.getOpt(VampirePlayer.java:141) ~[Vampirism-1.20.1-1.10.5.jar%23502!/:1.20.1-1.10.5]
        at de.teamlapen.vampirism.entity.ModEntityEventHandler.onEntityEquipmentChange(ModEntityEventHandler.java:122) ~[Vampirism-1.20.1-1.10.5.jar%23502!/:1.20.1-1.10.5]
        at de.teamlapen.vampirism.entity.__ModEntityEventHandler_onEntityEquipmentChange_LivingEquipmentChangeEvent.invoke(.dynamic) ~[Vampirism-1.20.1-1.10.5.jar%23502!/:1.20.1-1.10.5]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraft.world.entity.LivingEntity.m_21319_(LivingEntityMixin.java:2410) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.world.entity.LivingEntity.m_21315_(LivingEntityMixin.java:2381) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntityMixin.java:2287) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.world.entity.player.Player.m_8119_(PlayerMixin.java:241) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerPlayNetHandlerMixin.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.network.Connection.m_129483_(ConnectionMixin.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23511!/:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Reproduce steps

Unknow

**Comment by Cheaterpaul** [comment]
This is only a warning and most likely happened when someone died. Nothing to worry about.
