### ISSUE TITLE
[Bug]: Crashed randomly when passing vampire hunter village(?) and aggroing them in creative

### ISSUE THREAD

**Issue by dalekfan** [TeamLapen/Vampirism#1333]
### Minecraft Version

1.20.x

### Forge Version

47.2.20

### Vampirism Version

1.10.6

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Game crashed after I flew over some sort of walled vampire hunter base with a tower.

### Relevant log output

```shell
[18:54:14] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.gossip.GossipContainer.m_26195_(java.util.UUID, java.util.function.Predicate)" because "this.f_35377_" is null
	at net.minecraft.world.entity.npc.Villager.m_35532_(Villager.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.random_something.villagesecurity.EventHandler.ifReputationBad(EventHandler.java:45) ~[villagesecurity-1.2-1.20.1.jar%23541!/:1.2-1.20.1]
	at net.random_something.villagesecurity.__EventHandler_ifReputationBad_LivingEvent.invoke(.dynamic) ~[villagesecurity-1.2-1.20.1.jar%23541!/:1.2-1.20.1]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingMakeBrain(ForgeHooks.java:258) ~[forge-1.20.1-47.2.20-universal.jar%23553!/:?]
	at net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:245) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.world.entity.Mob.<init>(Mob.java:123) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:14) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.world.entity.AgeableMob.<init>(AgeableMob.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.world.entity.npc.AbstractVillager.<init>(AbstractVillager.java:49) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.world.entity.npc.Villager.<init>(Villager.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.world.entity.npc.Villager.<init>(Villager.java:135) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at de.teamlapen.vampirism.blockentity.TotemBlockEntity.spawnVillagerDefault(TotemBlockEntity.java:1117) ~[Vampirism-1.20.1-1.10.6.jar%23538!/:1.20.1-1.10.6]
	at de.teamlapen.vampirism.blockentity.TotemBlockEntity.serverTickSecondNonCapture(TotemBlockEntity.java:578) ~[Vampirism-1.20.1-1.10.6.jar%23538!/:1.20.1-1.10.6]
	at de.teamlapen.vampirism.blockentity.TotemBlockEntity.serverTick(TotemBlockEntity.java:772) ~[Vampirism-1.20.1-1.10.6.jar%23538!/:1.20.1-1.10.6]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?]
	... 5 more
[18:54:15] [Server thread/FATAL]: Preparing crash report with UUID af818cd9-a0aa-4c9c-ab0c-65816c51e75d
[18:54:15] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Owner\curseforge\minecraft\Instances\Alex\crash-reports\crash-2024-02-01_18.54.14-server.txt
[18:54:15] [Server thread/INFO]: Stopping server
[18:54:15] [Server thread/INFO]: Saving players
[18:54:15] [Physics thread/INFO]: Deleting VSPhysicsPipelineStage resources!
[18:54:15] [Physics thread/WARN]: Physics pipeline ending
[18:54:15] [Render thread/FATAL]: Preparing crash report with UUID 6b68d2e8-2c12-4139-81d8-86788b1929f7
[18:54:15] [Server thread/INFO]: Saving worlds
```

### Reproduce steps

I am unsure how to replicate this, but I will try if this gets attention. 

### Other relevant mods

I have some mod that is causing mobs to attack me in creative? Perhaps Lucky's Smarter Mob Ai? Along with stuff like biomes o plenty, mystic's biomes, shattered world limits, and etc. I can send more info if needed but the modpack is huge and in heavy development. Liberty's villagers and productive villagers too.

**Comment by Cheaterpaul** [comment]
villagesecurity seems to be the cause of this.
