### ISSUE TITLE
[Bug]: `java.util.ConcurrentModificationException: null` with Domestication Innovation

### ISSUE THREAD

**Issue by MaxWasUnavailable** [TeamLapen/Vampirism#1346]
### Minecraft Version

1.20.1

### Forge Version

47.2.16

### Vampirism Version

1.10.6

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Crash to desktop. Was nearby a large vampire hunter camp.

### Relevant log output

```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?] {}
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?] {re:mixin}
	at net.minecraft.server.level.DistanceManager.m_140805_(DistanceManager.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterchunkloading.mixins.json:DistanceManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8489_(ServerChunkCache.java:273) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8456_(ServerChunkCache.java:217) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_6522_(Level.java:187) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:APP:neruina-common.mixins.json:WorldMixin,pl:mixin:A}
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.world.level.Level.m_6325_(Level.java:182) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:APP:neruina-common.mixins.json:WorldMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46745_(Level.java:178) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:APP:neruina-common.mixins.json:WorldMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_7702_(Level.java:560) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:APP:neruina-common.mixins.json:WorldMixin,pl:mixin:A}
	at de.teamlapen.vampirism.entity.VulnerableRemainsDummyEntity.getTile(VulnerableRemainsDummyEntity.java:185) ~[Vampirism-1.20.1-1.10.6.jar%23794!/:1.20.1-1.10.6] {re:classloading}
	at de.teamlapen.vampirism.entity.VulnerableRemainsDummyEntity.m_21223_(VulnerableRemainsDummyEntity.java:47) ~[Vampirism-1.20.1-1.10.6.jar%23794!/:1.20.1-1.10.6] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_6084_(LivingEntity.java:1507) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-badoptimizations.mixins.json:entitydata.MixinLivingEntity,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:saturn.mixins.json:allocations.fall_sounds.LivingEntityMixin,pl:mixin:APP:secondchanceforge.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:etched.mixins.json:client.ClientLivingEntityMixin,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_cap_retrieval.LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:vinery-common.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:MHFMixinLivingEntity,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:attributeslib.mixins.json:LivingEntityMixin,pl:mixin:APP:mixins.cofhcore.json:LivingEntityMixin,pl:mixin:APP:reactive.mixins.json:LivingEntityGravityMixin,pl:mixin:APP:werewolves.mixins.json:LivingEntityAccessor,pl:mixin:APP:ecologics-common.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.LivingEntityGravityMixin,pl:mixin:APP:tetra.mixins.json:LivingEntityMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:eidolon.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:relics.mixins.json:MixinLivingEntity,pl:mixin:APP:ramcompat.mixins.json:LivingEntityMixin,pl:mixin:APP:dummmmmmy-common.mixins.json:LivingEntityMixin,pl:mixin:APP:mixins.biomancy.json:LivingEntityAccessor,pl:mixin:APP:mixins.biomancy.json:LivingEntityMixin,pl:mixin:APP:mixins.biomancy.json:PhantomMixin,pl:mixin:APP:caupona.mixins.json:LivingEntityMixin,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:nyfsspiders.mixins.json:LivingEntityMixin,pl:mixin:APP:nyfsspiders.mixins.json:LivingEntityClientMixin,pl:mixin:APP:wizards_reborn.mixins.json:LivingEntityMixin,pl:mixin:APP:alexscaves.mixins.json:LivingEntityMixin,pl:mixin:APP:snowyspirit-common.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:scena.mixins.json:common.LivingEntityEquipmentSlotMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at com.github.alexthe668.domesticationinnovation.server.CommonProxy.onEntityLeaveWorld(CommonProxy.java:145) ~[domesticationinnovation-1.7.1-1.20.1.jar%23596!/:1.7.1-1.20.1] {re:classloading}
	at com.github.alexthe668.domesticationinnovation.server.__CommonProxy_onEntityLeaveWorld_EntityLeaveLevelEvent.invoke(.dynamic) ~[domesticationinnovation-1.7.1-1.20.1.jar%23596!/:1.7.1-1.20.1] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141981_(ServerLevel.java:1554) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141981_(ServerLevel.java:1488) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157580_(PersistentEntitySectionManager.java:140) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:PersistentEntitySectionManagerMixin,pl:mixin:A}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157543_(PersistentEntitySectionManager.java:175) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:PersistentEntitySectionManagerMixin,pl:mixin:A}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177) ~[?:?] {}
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:183) ~[?:?] {re:mixin}
	at java.util.Spliterators$LongIteratorSpliterator.forEachRemaining(Spliterators.java:2046) ~[?:?] {}
	at java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:775) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157527_(PersistentEntitySectionManager.java:160) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:PersistentEntitySectionManagerMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_287207_(PersistentEntitySectionManager.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:smoothchunk.mixins.json:PersistentEntitySectionManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_287285_(ChunkMap.java:1307) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:krypton.mixins.json:shared.network.avoidwork.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:smallships-common-soft.mixins.json:leashing.ChunkMapMixin,pl:mixin:APP:enhancedcelestials.mixins.json:access.ChunkMapAccess,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkHolder.m_287189_(ChunkHolder.java:346) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,re:classloading,pl:mixin:APP:chunksending.mixins.json:ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkHolder.m_143003_(ChunkHolder.java:416) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,re:classloading,pl:mixin:APP:chunksending.mixins.json:ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.server.level.DistanceManager.m_183906_(DistanceManager.java:120) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterchunkloading.mixins.json:DistanceManagerMixin,pl:mixin:A}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraft.server.level.DistanceManager.m_140805_(DistanceManager.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterchunkloading.mixins.json:DistanceManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8489_(ServerChunkCache.java:273) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:545) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:smoothchunk.mixins.json:ServerChunkCacheMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23820!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```

### Reproduce steps

1. Load/create world
2. Be next to vampire hunter camp
3. Wait around / fly around a bit
4. Crash

### Other relevant mods

Embeddium, Oculus

**Comment by MaxWasUnavailable** [comment]
Also reported at Domestication Innovation, here: https://github.com/AlexModGuy/DomesticationInnovation/issues/197

**Comment by Cheaterpaul** [comment]
On further investigation i can not see why this can crash unless another third party mod or framework does something.

Please reopen if this issue it still present.
