### ISSUE TITLE
[Modcompat]: [1.19.2] Crash when Campanion tent placement render intersects with Vampirism claimed village totem

### ISSUE THREAD

**Issue by CrossroadsWanderer** [TeamLapen/Vampirism#1407]
### Minecraft Version

1.19.2

### Forge Version

43.4.0

### Vampirism Version

1.9.5

### Incompatible mod

Campanion 4.1.2+forge

### Singleplayer/Multiplayer

Singleplayer

### What happened?

When holding a Campanion tent as the active item, when the rendering of where the tent will place intersects with a claimed village totem, the game instantly crashes.

### Reproduce steps

1. Load a single player world.
2. Pick a small or large Campanion tent out of the creative menu or craft one.
3. Find a village with an intact, claimed village totem. If the top of the totem is missing or neutral, the crash does not occur.
4. Select the tent as the active item, causing a translucent rendering of the tent to appear and show what it will look like when placed.
5. Move the rendering until it intersects with the village totem. The game will crash instantly.

Note: In an instance that also contains Embeddium (version 0.3.18), the crash report will indicate that Embeddium is involved in the crash. The crash happens regardless of whether Embeddium is in the instance.

### Relevant log output

```shell
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-08-18 23:46:44
Description: Tent Rendering Block Entity

java.lang.IllegalStateException: Not filled all elements of the vertex
	at com.mojang.blaze3d.vertex.BufferBuilder.m_5752_(BufferBuilder.java:288) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.font.glyphs.BakedGlyph.m_5626_(BakedGlyph.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92787_(Font.java:357) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font$StringRenderOutput.m_6411_(Font.java:286) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.util.StringDecomposer.m_14332_(StringDecomposer.java:17) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.util.StringDecomposer.m_14317_(StringDecomposer.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.util.FormattedCharSequence.m_13736_(FormattedCharSequence.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92926_(Font.java:352) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92866_(Font.java:201) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92733_(Font.java:134) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92841_(Font.java:130) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at de.teamlapen.vampirism.client.renderer.blockentity.TotemBESR.renderFactionName(TotemBESR.java:68) ~[Vampirism-1.19.2-1.9.5.jar%23144!/:1.9.5] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.vampirism.client.renderer.blockentity.TotemBESR.render(TotemBESR.java:47) ~[Vampirism-1.19.2-1.9.5.jar%23144!/:1.9.5] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.vampirism.client.renderer.blockentity.TotemBESR.m_6922_(TotemBESR.java:19) ~[Vampirism-1.19.2-1.9.5.jar%23144!/:1.9.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.renderBlockEntity(BuiltTentItemRenderer.java:61) ~[Campanion-forge-1.19.2-4.1.2+forge.jar%23143!/:4.1.2+forge] {re:mixin,re:classloading}
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.renderFakeBlock(BuiltTentItemRenderer.java:53) ~[Campanion-forge-1.19.2-4.1.2+forge.jar%23143!/:4.1.2+forge] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzo000$renderLevel(LevelRenderer.java:3154) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1234) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:campanion.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:campanion.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.0.jar%23140!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Vampirism (vampirism), Version: 1.9.5
		Issue tracker URL: https://github.com/TeamLapen/Vampirism/issues
		at TRANSFORMER/vampirism@1.9.5/de.teamlapen.vampirism.client.renderer.blockentity.TotemBESR.renderFactionName(TotemBESR.java:68)

	Campanion (campanion), Version: 4.1.2+forge
		Issue tracker URL: https://github.com/TerraformersMC/Campanion/issues
		at TRANSFORMER/campanion@4.1.2+forge/com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.renderBlockEntity(BuiltTentItemRenderer.java:61)
Stacktrace:
	at com.mojang.blaze3d.vertex.BufferBuilder.m_5752_(BufferBuilder.java:288) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.font.glyphs.BakedGlyph.m_5626_(BakedGlyph.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92787_(Font.java:357) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font$StringRenderOutput.m_6411_(Font.java:286) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.util.StringDecomposer.m_14332_(StringDecomposer.java:17) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.util.StringDecomposer.m_14317_(StringDecomposer.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.util.FormattedCharSequence.m_13736_(FormattedCharSequence.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92926_(Font.java:352) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92866_(Font.java:201) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92733_(Font.java:134) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at net.minecraft.client.gui.Font.m_92841_(Font.java:130) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading}
	at de.teamlapen.vampirism.client.renderer.blockentity.TotemBESR.renderFactionName(TotemBESR.java:68) ~[Vampirism-1.19.2-1.9.5.jar%23144!/:1.9.5] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.vampirism.client.renderer.blockentity.TotemBESR.render(TotemBESR.java:47) ~[Vampirism-1.19.2-1.9.5.jar%23144!/:1.9.5] {re:classloading,pl:runtimedistcleaner:A}
	at de.teamlapen.vampirism.client.renderer.blockentity.TotemBESR.m_6922_(TotemBESR.java:19) ~[Vampirism-1.19.2-1.9.5.jar%23144!/:1.9.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.renderBlockEntity(BuiltTentItemRenderer.java:61) ~[Campanion-forge-1.19.2-4.1.2+forge.jar%23143!/:4.1.2+forge] {re:mixin,re:classloading}
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.renderFakeBlock(BuiltTentItemRenderer.java:53) ~[Campanion-forge-1.19.2-4.1.2+forge.jar%23143!/:4.1.2+forge] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzo000$renderLevel(LevelRenderer.java:3154) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1234) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Block Entity Details --
Details:
	Name: vampirism:totem // de.teamlapen.vampirism.blockentity.TotemBlockEntity
	Block: Block{vampirism:totem_top_vampirism_vampire}
	Block location: World: (1077,72,-783), Section: (at 5,8,1 in 67,4,-49; chunk contains blocks 1072,-64,-784 to 1087,319,-769), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,-64,-1024 to 1535,319,-513)
	Block: Block{vampirism:totem_top_vampirism_vampire}
	Block location: World: (1077,72,-783), Section: (at 5,8,1 in 67,4,-49; chunk contains blocks 1072,-64,-784 to 1087,319,-769), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,-64,-1024 to 1535,319,-513)
Stacktrace:
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.renderBlockEntity(BuiltTentItemRenderer.java:61) ~[Campanion-forge-1.19.2-4.1.2+forge.jar%23143!/:4.1.2+forge] {re:mixin,re:classloading}
	at com.terraformersmc.campanion.client.renderer.item.BuiltTentItemRenderer.renderFakeBlock(BuiltTentItemRenderer.java:53) ~[Campanion-forge-1.19.2-4.1.2+forge.jar%23143!/:4.1.2+forge] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zzo000$renderLevel(LevelRenderer.java:3154) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1234) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:campanion.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:campanion.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.0.jar%23140!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}


-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['XroadsWanderer'/63, l='ClientLevel', x=1080.51, y=73.12, z=-772.02]]
	Chunk stats: 5041, 3653
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,116,32), Section: (at 0,4,0 in 0,7,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5607 game time, 5607 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2280) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:campanion.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:717) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:campanion.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23145!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.0.jar%23140!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23127!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.4.0-192-generic
	Java Version: 17.0.12, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 2218521712 bytes (2115 MiB) / 4651483136 bytes (4436 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: GP102 [GeForce GTX 1080 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1b06
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 23828.89
	Virtual memory used (MB): 15908.57
	Swap memory total (MB): 7812.00
	Swap memory used (MB): 2.00
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 535.183.01, NVIDIA Corporation
	Window size: 1600x869
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['XroadsWanderer'/63, l='ServerLevel[Test 1]', x=1080.51, y=73.12, z=-772.02]]
	Data Packs: vanilla, mod:campanion (incompatible), mod:forge, mod:vampirism (incompatible)
	World Generation: Experimental
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.4.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.4.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.4.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.4.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.4.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Campanion-forge-1.19.2-4.1.2+forge.jar            |Campanion                     |campanion                     |4.1.2+forge         |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.4.0-universal.jar                 |Forge                         |forge                         |43.4.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Vampirism-1.19.2-1.9.5.jar                        |Vampirism                     |vampirism                     |1.9.5               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d6adaf5a-de6a-41e4-8b86-4079bf069ceb
	FML: 43.4
	Forge: net.minecraftforge:43.4.0
```

**Comment by maxanier** [comment]
Thank you for reporting. 
I am not really sure how to fix this on our end.
I have reported this to the Campanion Devs, hopefully they have an idea or can implement a fix.

**Comment by CrossroadsWanderer** [comment]
Yeah, I wasn't sure which mod was more responsible for the issue and I wasn't sure whether the Campanion devs would fix it if it was coming from that mod because it seems like Campanion hasn't been updated in a while. But I figured if nothing else, it would be good to put a crash report out there in case anyone else runs into the same problem.

Thanks for looking deeper into it and reporting the specifics to the Campanion devs, in case there is a possibility of getting a fix.

**Comment by Cheaterpaul** [comment]
Campanion is unresponsive
