### ISSUE TITLE
[Modcompat]: From another world doesn't know how to convert hunter_Imob variants (should be a crash)

### ISSUE THREAD

**Issue by FuryJack07** [TeamLapen/Vampirism#1437]
### Minecraft Version

1.20.x

### Forge Version

47.3.7

### Vampirism Version

1.10.11

### Incompatible mod

From Another World 1.2A.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Neurina caught entity.fromanotherworld.transition giving a ticking error

### Reproduce steps

1. load a single player world
2. make a hunter entity get assimilated
3. become a vampire to turn that hunter into a hunter_Imob (works for advanced hunters too)
4. trigger the transition by attacking the hunter_Imob
5. the game should crash (unless you have Neurina installed, which will just suspend the entity to not let the game die)

### Relevant log output

```shell
Neurina gave this report:

java.lang.RuntimeException: No appropriate Thing transformations available for the provided context!
Context Information:
Previous Form ID: vampirism:advanced_hunter_imob
Position: (-0.30000001192092896, 71.0, 9.300000011920929)
	at TRANSFORMER/fromanotherworld@1.2A.1-forge/mod.acats.fromanotherworld.transformation.FormSelector.allowedTransformations(FormSelector.java:59)
	at TRANSFORMER/fromanotherworld@1.2A.1-forge/mod.acats.fromanotherworld.transformation.FormSelector.getWeightedRandomFor(FormSelector.java:14)
	at TRANSFORMER/fromanotherworld@1.2A.1-forge/mod.acats.fromanotherworld.entity.thing.TransitionEntity.becomeResultant(TransitionEntity.java:217)
	at TRANSFORMER/fromanotherworld@1.2A.1-forge/mod.acats.fromanotherworld.entity.thing.TransitionEntity.m_8119_(TransitionEntity.java:173)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$143(Level.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.wrapOperation$chg000$catchTickingEntities$notTheCauseOfTickLag(Level.java:2540)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)



I'll report this to FAW too, in case they're the ones handling transformations from this mod
```

**Comment by Cheaterpaul** [comment]
This is entirely the fault of From Another World. I have no idea what they do, but they force the game to crash for some reason.

Yes, please report this to them.

**Comment by maxanier** [comment]
`From Another World` does not seem to be updated anymore.
There is a similar bug report on their issue tracker:
https://github.com/FakeACat/FromAnotherWorld-Architectury/issues/5

I haven't looked into how that mod works, but maybe this problem can be solved by adding `hunter_imob` (same for advanced, and vampires) to this list:
https://github.com/FakeACat/FromAnotherWorld-Architectury/blob/a484e87f1efe58898af1072e1c2ab811dfea5ecb/common/src/main/resources/resourcepacks/fromanotherworld_compat_vampirism/data/fromanotherworld/tags/entity_types/humanoids.json#L5
Then add load it as a datapack.

Alternatively, the workaround from the linked issue (delete the `humanoids.json` from the mod `.jar`) should work, but remove any Vampirism related functionality from FAW

**Comment by maxanier** [comment]
If anyone has created such a datapack, please share here.
