### ISSUE TITLE
[Bug]: "Vampire Integrations" mod error with Jade mod (WAILA)

### ISSUE THREAD

**Issue by SrPedro345** [TeamLapen/Vampirism#1446]
### Minecraft Version

1.18.x

### (Neo)Forge Version

40.2.21

### Vampirism Version

1.8.8

### Singleplayer/Multiplayer

Singleplayer

### What happened?

When using Jade, Vampirism and Vampirism integrations, when aiming at a low enemy, an "Error" appears and a log is left in my folder.

### Relevant log output

10/30/2024 - 23:16:05
class de.teamlapen.vampirism_integrations.waila.CreatureDataProvider
java.lang.AbstractMethodError: Receiver class de.teamlapen.vampirism_integrations.waila.CreatureDataProvider does not define or inherit an implementation of the resolved method 'abstract void appendTooltip(mcp.mobius.waila.api.ITooltip, mcp.mobius.waila.api.EntityAccessor, mcp.mobius.waila.api.config.IPluginConfig)' of interface mcp.mobius.waila.api.IEntityComponentProvider.
	at TRANSFORMER/jade@5.3.2/mcp.mobius.waila.impl.EntityAccessorImpl._gatherComponents(EntityAccessorImpl.java:76)
	at TRANSFORMER/jade@5.3.2/mcp.mobius.waila.overlay.WailaTickHandler.gatherComponents(WailaTickHandler.java:138)
	at TRANSFORMER/jade@5.3.2/mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:114)
	at TRANSFORMER/jade@5.3.2/mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:147)
	at net.minecraftforge.eventbus.ASMEventHandler_712_WailaClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.2.21/net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:921)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1754)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1021)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.21/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

10/31/2024 - 21:59:27
class de.teamlapen.vampirism_integrations.waila.CreatureDataProvider
java.lang.AbstractMethodError: Receiver class de.teamlapen.vampirism_integrations.waila.CreatureDataProvider does not define or inherit an implementation of the resolved method 'abstract void appendTooltip(mcp.mobius.waila.api.ITooltip, mcp.mobius.waila.api.EntityAccessor, mcp.mobius.waila.api.config.IPluginConfig)' of interface mcp.mobius.waila.api.IEntityComponentProvider.
	at TRANSFORMER/jade@5.3.2/mcp.mobius.waila.impl.EntityAccessorImpl._gatherComponents(EntityAccessorImpl.java:76)
	at TRANSFORMER/jade@5.3.2/mcp.mobius.waila.overlay.WailaTickHandler.gatherComponents(WailaTickHandler.java:138)
	at TRANSFORMER/jade@5.3.2/mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:114)
	at TRANSFORMER/jade@5.3.2/mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:147)
	at net.minecraftforge.eventbus.ASMEventHandler_705_WailaClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.2.21/net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:921)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1754)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1021)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.21/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

### Reproduce steps

1. I open minecraft
2. I create my world
3. I point to an enemy or something that shows the information in the Jade mod
4. Below said information a text appears saying <Error>

**Comment by Cheaterpaul** [comment]
That is because Jade and Waila/WTHIT use the same names. Jade only used separate names name later.

There is not really a thing that can be done about it, than using a newer Minecraft version
