### ISSUE TITLE
[Bug]: console error  Cannot get Faction player capability. This might break mod functionality.

### ISSUE THREAD

**Issue by makegodhere** [TeamLapen/Vampirism#1455]
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.3.0

### Vampirism Version

1.10.11

### Singleplayer/Multiplayer

Server

### What happened?

console error without crash and brokens

### Relevant log output

```
[08:27:34] [Server thread/WARN] [de.te.va.en.fa.FactionPlayerHandler/]: Cannot get Faction player capability. This might break mod functionality.
java.lang.Throwable: null
        at de.teamlapen.vampirism.entity.factions.FactionPlayerHandler.getOpt(FactionPlayerHandler.java:71) ~[Vampirism-1.20.1-1.10.11.jar%23541!/:1.20.1-1.10.11] {re:classloading}
        at de.teamlapen.vampirism.entity.player.ModPlayerEventHandler.onPlayerGameMode(ModPlayerEventHandler.java:548) ~[Vampirism-1.20.1-1.10.11.jar%23541!/:1.20.1-1.10.11] {re:mixin,re:classloading,pl:mixin:A}
        at de.teamlapen.vampirism.entity.player.__ModPlayerEventHandler_onPlayerGameMode_PlayerChangeGameModeEvent.invoke(.dynamic) ~[Vampirism-1.20.1-1.10.11.jar%23541!/:1.20.1-1.10.11] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.common.ForgeHooks.onChangeGameType(ForgeHooks.java:824) ~[forge-1.20.1-47.3.0-universal.jar%23568!/:?] {re:mixin,re:classloading,pl:mixin:APP:apoli.mixins.json:forge.ForgeHooksMixin,pl:mixin:APP:tombstone.mixins.json:ForgeHooksMixin,pl:mixin:APP:locks.mixins.json:accessor.ForgeHooksAccessor,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayer.m_143403_(ServerPlayer.java:1242) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:mixins.medievalend.json:ServerPlayerMix,pl:mixin:APP:servercore.common.mixins.json:optimizations.players.ServerPlayerMixin,pl:mixin:APP:missions-common.mixins.json:events.DrinkHandler,pl:mixin:APP:puffish_skills.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:pehkui.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:glitchcore.forge.mixins.json:MixinServerPlayer,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:numismatics-common.mixins.json:MixinServerPlayer,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:apugli.mixins.json:common.accessor.ServerPlayerEntityAccessor,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
        at top.seraphjack.simplelogin.server.handler.plugins.RestrictGameType.preLogout(RestrictGameType.java:28) ~[SimpleLogin-1.20.1-1.0.2-all.jar%23513!/:1.0.2] {re:classloading}
        at top.seraphjack.simplelogin.server.handler.PlayerLoginHandler.lambda$playerLeave$4(PlayerLoginHandler.java:110) ~[SimpleLogin-1.20.1-1.0.2-all.jar%23513!/:1.0.2] {re:classloading,pl:runtimedistcleaner:A}
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4783) ~[?:?] {}
        at top.seraphjack.simplelogin.server.handler.PlayerLoginHandler.playerLeave(PlayerLoginHandler.java:110) ~[SimpleLogin-1.20.1-1.0.2-all.jar%23513!/:1.0.2] {re:classloading,pl:runtimedistcleaner:A}
        at top.seraphjack.simplelogin.server.ServerSideEventHandler.playerLeave(ServerSideEventHandler.java:35) ~[SimpleLogin-1.20.1-1.0.2-all.jar%23513!/:1.0.2] {re:classloading,pl:runtimedistcleaner:A}
        at top.seraphjack.simplelogin.server.__ServerSideEventHandler_playerLeave_PlayerLoggedOutEvent.invoke(.dynamic) ~[SimpleLogin-1.20.1-1.0.2-all.jar%23513!/:1.0.2] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedOut(ForgeEventFactory.java:880) ~[forge-1.20.1-47.3.0-universal.jar%23568!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}
        at net.minecraft.server.players.PlayerList.m_11286_(PlayerList.java:346) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_playerlist_sendworldinfo,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_playerlist_sendworldinfo,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerGamePacketListenerImpl.java:1136) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl,pl:mixin:APP:apoli.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:APP:servercore.common.mixins.json:features.misc.ServerGamePacketListenerImplMixin,pl:mixin:APP:graveyard-common.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:pehkui.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:pehkui.mixins.json:compat1204minus.ServerPlayNetworkHandlerMixin,pl:mixin:APP:pehkui.mixins.json:reach.compat1204minus.ServerPlayNetworkHandlerMixin,pl:mixin:APP:pehkui.mixins.json:reach.compat1204minus.compat119plus.ServerPlayNetworkHandlerMixin,pl:mixin:APP:common.mixins.scholar.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:APP:numismatics.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:copycats-forge.mixins.json:network.ServerGamePacketListenerImplMixin,pl:mixin:APP:apugli.mixins.json:common.ServerPlayNetworkHandlerMixin,pl:mixin:APP:apugli.forge.mixins.json:common.ServerGamePacketListenerImplMixin,pl:mixin:APP:connectivity.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.Connection.m_129541_(Connection.java:432) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:AdvancedPacketErrorLogging,pl:mixin:APP:proxy_protocol_support.mixins.json:ProxyProtocolAddressSetter,pl:mixin:APP:connectivity.mixins.json:ConnectionMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:157) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:mixin,re:classloading,pl:mixin:APP:proxy_protocol_support.mixins.json:ProxyProtocolImplementation,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin,pl:mixin:APP:missions-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin,pl:mixin:APP:missions-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin,pl:mixin:APP:missions-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23563!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:servercore.common.mixins.json:features.misc.MinecraftServerMixin,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:servercore.common.mixins.json:MinecraftServerMixin,pl:mixin:APP:missions-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
```

**Comment by maxanier** [comment]
Something unexpected is happening here. Maybe due to `top.seraphjack.simplelogin`, maybe for other reasons.

Is the console spammed with this or does this only happen if a player leaves the server?
As long as there are no problems, please just ignore this. It is meant to help debugging problems.
