### ISSUE TITLE
SMP compatbility issue: targetAngle not found

### ISSUE THREAD

**Issue by LemADEC** [TeamLapen/Vampirism#146]
As of Vampirism-1.10.2-1.1.0-alpha+02-23-15-57.jar with forge-1.10.2-12.18.3.2239-universal.jar and spongeforge-1.10.2-2221-5.2.0-BETA-2219.jar, there's a console spam about targetAngle field being not found.

```
[14:14:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NoSuchFieldError: targetAngle
[14:14:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    at de.teamlapen.vampirism.entity.hunter.EntityBasicHunter.<init>(EntityBasicHunter.java:79)
[14:14:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]:    ... 16 more
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]: java.lang.reflect.InvocationTargetException
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at sun.reflect.GeneratedConstructorAccessor191.newInstance(Unknown Source)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at net.minecraft.entity.EntityList.func_75620_a(EntityList.java:150)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at de.teamlapen.lib.lib.util.SimpleSpawnerLogic.updateSpawner(SimpleSpawnerLogic.java:103)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at de.teamlapen.vampirism.tileentity.TileTent.func_73660_a(TileTent.java:99)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2798)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjn000(WorldServer.java:2785)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at net.minecraft.world.World.func_72939_s(World.java:5999)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2153)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[14:14:23] [Server thread/INFO] [STDERR]: [net.minecraft.entity.EntityList:func_75620_a:154]:   at java.lang.Thread.run(Thread.java:745)
```

**Comment by maxanier** [comment]
Thx for reporting. Fixed and new alpha released.
https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2389642
