### ISSUE TITLE
[Bug]: Vampirism crashes when pressing V

### ISSUE THREAD

**Issue by DanDan-Cantsleep** [TeamLapen/Vampirism#1466]
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.3.12

### Vampirism Version

1.10.12

### Singleplayer/Multiplayer

Server

### What happened?

Hi! I downloaded Vampirism for 1.20.1 in a server with friends, back when we played in 1.17.1 we didn't had any problem when pressing V to drink blood from animals but now every time (at least for me) i press V the game frozes and kicks me out of the server and i can't find any solution  :/
Edit: My friend doesn't have these crashes but she mentions the V button doesn't work and won't suck blood neither, tried changing the keys but same issue

### Relevant log output

[30Dec2024 00:35:02.122] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: effect type cannot be null
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: com.mrcrayfish.framework.event.ForgeEvents@6c15e670 onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		2: ASM: de.teamlapen.vampirism.entity.ModEntityEventHandler@1f8a4e49 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		3: ASM: de.teamlapen.lib.entity.EntityEventHandler@48bf7e5e onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
java.lang.IllegalArgumentException: effect type cannot be null
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at TRANSFORMER/arclight@1.20.1-1.0.6-SNAPSHOT-158c22b/org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:52)
	at TRANSFORMER/arclight@1.20.1-1.0.6-SNAPSHOT-158c22b/org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:72)
	at TRANSFORMER/arclight@1.20.1-1.0.6-SNAPSHOT-158c22b/org.bukkit.craftbukkit.v1_20_R1.potion.CraftPotionUtil.toBukkit(CraftPotionUtilMixin.java:113)
	at TRANSFORMER/arclight@1.20.1-1.0.6-SNAPSHOT-158c22b/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1668)
	at TRANSFORMER/arclight@1.20.1-1.0.6-SNAPSHOT-158c22b/org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1663)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_147207_(LivingEntityMixin.java:3885)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_7292_(LivingEntityMixin.java:921)
	at TRANSFORMER/vampirism@1.10.12/de.teamlapen.vampirism.entity.player.vampire.VampirePlayer.updateFeeding(VampirePlayer.java:1431)
	at TRANSFORMER/vampirism@1.10.12/de.teamlapen.vampirism.entity.player.vampire.VampirePlayer.onUpdate(VampirePlayer.java:894)
	at TRANSFORMER/forge@47.3.12/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137)
	at TRANSFORMER/vampirism@1.10.12/de.teamlapen.lib.entity.EntityEventHandler.onLivingUpdate(EntityEventHandler.java:80)
	at TRANSFORMER/vampirism@1.10.12/de.teamlapen.lib.entity.__EntityEventHandler_onLivingUpdate_LivingTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.12/net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooksMixin.java:264)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntityMixin.java:2258)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(PlayerMixin.java:241)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:467)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerPlayNetHandlerMixin.java:262)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(ConnectionMixin.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:283)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2071)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
	at java.base/java.lang.Thread.run(Thread.java:840)

### Reproduce steps

1- Load the multiplayer server and join
2- Being a level 1 Vampire pick a cat or a pig
3- Hold press V
4- Game crashes and returns to multilayer menu

**Comment by Cheaterpaul** [comment]
can you share the whole crash-report, this is just an excerpt

**Comment by DanDan-Cantsleep** [comment]
> can you share the whole crash-report, this is just an excerpt

Sure! Y copied from there all the way bellow (i hope is the right one-)

[30Dec2024 00:35:02.181] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /181.168.89.82:51621
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerPlayerMixin_Optimize,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerPlayNetHandlerMixin.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(ConnectionMixin.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ConnectionMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2071) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
Caused by: java.lang.IllegalArgumentException: effect type cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%23108!/:?] {re:mixin}
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:52) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading}
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:72) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading}
	at org.bukkit.craftbukkit.v1_20_R1.potion.CraftPotionUtil.toBukkit(CraftPotionUtilMixin.java:113) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftPotionUtilMixin,pl:mixin:A}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1668) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1663) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at net.minecraft.world.entity.LivingEntity.m_147207_(LivingEntityMixin.java:3885) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:refurbished_furniture.common.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at net.minecraft.world.entity.LivingEntity.m_7292_(LivingEntityMixin.java:921) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:refurbished_furniture.common.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at de.teamlapen.vampirism.entity.player.vampire.VampirePlayer.updateFeeding(VampirePlayer.java:1431) ~[Vampirism-1.20.1-1.10.12.jar%23191!/:1.20.1-1.10.12] {re:classloading}
	at de.teamlapen.vampirism.entity.player.vampire.VampirePlayer.onUpdate(VampirePlayer.java:894) ~[Vampirism-1.20.1-1.10.12.jar%23191!/:1.20.1-1.10.12] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137) ~[forge-1.20.1-47.3.12-universal.jar%23200!/:?] {re:classloading}
	at de.teamlapen.lib.entity.EntityEventHandler.onLivingUpdate(EntityEventHandler.java:80) ~[Vampirism-1.20.1-1.10.12.jar%23191!/:1.20.1-1.10.12] {re:classloading}
	at de.teamlapen.lib.entity.__EntityEventHandler_onLivingUpdate_LivingTickEvent.invoke(.dynamic) ~[Vampirism-1.20.1-1.10.12.jar%23191!/:1.20.1-1.10.12] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooksMixin.java:264) ~[forge-1.20.1-47.3.12-universal.jar%23200!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.forge.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntityMixin.java:2258) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:refurbished_furniture.common.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at net.minecraft.world.entity.player.Player.m_8119_(PlayerMixin.java:241) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.PlayerMixin,pl:mixin:APP:betterarcheology.mixins.json:ElytraStartupMixin,pl:mixin:APP:vampirism.mixins.json:MixinPlayerEntity,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerPlayerMixin_Optimize,pl:mixin:A}

**Comment by DanDan-Cantsleep** [comment]
> can you share the whole crash-report, this is just an excerpt

Sure! Y copied from there all the way bellow (i hope is the right one-)

[30Dec2024 00:35:02.181] [Server thread/WARN] [net.minecraft.server.network.ServerConnectionListener/]: Failed to handle packet for /181.168.89.82:51621
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerPlayerMixin_Optimize,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerPlayNetHandlerMixin.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(ConnectionMixin.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ConnectionMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2071) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
Caused by: java.lang.IllegalArgumentException: effect type cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%23108!/:?] {re:mixin}
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:52) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading}
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:72) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading}
	at org.bukkit.craftbukkit.v1_20_R1.potion.CraftPotionUtil.toBukkit(CraftPotionUtilMixin.java:113) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftPotionUtilMixin,pl:mixin:A}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1668) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactoryMixin.java:1663) ~[arclight-1.20.1-1.0.6-SNAPSHOT-158c22b.jar%23178!/:arclight-1.20.1-1.0.6-SNAPSHOT-158c22b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
	at net.minecraft.world.entity.LivingEntity.m_147207_(LivingEntityMixin.java:3885) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:refurbished_furniture.common.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at net.minecraft.world.entity.LivingEntity.m_7292_(LivingEntityMixin.java:921) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:refurbished_furniture.common.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at de.teamlapen.vampirism.entity.player.vampire.VampirePlayer.updateFeeding(VampirePlayer.java:1431) ~[Vampirism-1.20.1-1.10.12.jar%23191!/:1.20.1-1.10.12] {re:classloading}
	at de.teamlapen.vampirism.entity.player.vampire.VampirePlayer.onUpdate(VampirePlayer.java:894) ~[Vampirism-1.20.1-1.10.12.jar%23191!/:1.20.1-1.10.12] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137) ~[forge-1.20.1-47.3.12-universal.jar%23200!/:?] {re:classloading}
	at de.teamlapen.lib.entity.EntityEventHandler.onLivingUpdate(EntityEventHandler.java:80) ~[Vampirism-1.20.1-1.10.12.jar%23191!/:1.20.1-1.10.12] {re:classloading}
	at de.teamlapen.lib.entity.__EntityEventHandler_onLivingUpdate_LivingTickEvent.invoke(.dynamic) ~[Vampirism-1.20.1-1.10.12.jar%23191!/:1.20.1-1.10.12] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooksMixin.java:264) ~[forge-1.20.1-47.3.12-universal.jar%23200!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.forge.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntityMixin.java:2258) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:refurbished_furniture.common.mixins.json:LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:activationrange.entity.LivingEntityMixin_ActivationRange,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ApotheosisCompatMixin,pl:mixin:APP:mixins.arclight.core.json:world.entity.LivingEntityMixin$ObscureApiCompat,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at net.minecraft.world.entity.player.Player.m_8119_(PlayerMixin.java:241) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.PlayerMixin,pl:mixin:APP:betterarcheology.mixins.json:ElytraStartupMixin,pl:mixin:APP:vampirism.mixins.json:MixinPlayerEntity,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayerMixin.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23195!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.entity.player.ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerPlayerMixin_Optimize,pl:mixin:A}

**Comment by DanDan-Cantsleep** [comment]
Updates over the issue: Now it only did not affect the blood feed system, me and my friend found a Hunters fortress/camp (the big ones) and started kicking us out the server with the message "Internal Server Error" i checked the new log and the previous one and they seem to have the same problem, my apologies btw over closing and opening this 😭 Github on phone is weird
(Triend unstalling the mod from the server and download it again but it didn't work)
