### ISSUE TITLE
Client NPE when connecting to server

### ISSUE THREAD

**Issue by LemADEC** [TeamLapen/Vampirism#293]
## Versions
- Minecraft:      1.10.2
- Forge:            12.18.3.2511
- Vampirism:    Vampirism-1.10.2-1.2.5

## Issue Description
Random client crash while connecting to a server.

## Reproduce Steps
Connect to server

## Additional Information
```
java.lang.NullPointerException: Unexpected error
	at de.teamlapen.vampirism.player.vampire.VampirePlayer.get(VampirePlayer.java:86)
	at de.teamlapen.vampirism.client.render.RenderHandler.onClientTick(RenderHandler.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_962_RenderHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.teamlapen.vampirism.player.vampire.VampirePlayer.get(VampirePlayer.java:86)
	at de.teamlapen.vampirism.client.render.RenderHandler.onClientTick(RenderHandler.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_962_RenderHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by maxanier** [comment]
Does this occur frequently?

**Comment by LemADEC** [comment]
I've just seen it once while working on another issue.

**Comment by maxanier** [comment]
Ok, then I guess it origin of this crash is just a very rare coincidence which is not supposed to happen (in vanilla MC).
I won't release a bugfix version for this, unless it occurs more frequently, but I will include the workaround/fix in future versions
