### ISSUE TITLE
Some spam errors in client log

### ISSUE THREAD

**Issue by avescarelo** [TeamLapen/Vampirism#349]
## Versions
- Minecraft: 1.12.2                   
- Forge:  2750                     
- Vampirism: Vampirism-1.12.2-1.5.0-alpha+08-16-14-13                                            

## Issue Description
Before i installed the GuideAPI, i get this erros in client log.

## Additional Information
(client) latest.log: https://gist.github.com/pingvikin/b87f1074c15c6cc3d7b9366440a22daa

[16:40:11] [main/ERROR]: Catching
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
	at java.util.Formatter$FormatSpecifier.failMismatch(Unknown Source) ~[?:1.8.0_171]
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Unknown Source) ~[?:1.8.0_171]
	at java.util.Formatter$FormatSpecifier.checkGeneral(Unknown Source) ~[?:1.8.0_171]
	at java.util.Formatter$FormatSpecifier.<init>(Unknown Source) ~[?:1.8.0_171]
	at java.util.Formatter.parse(Unknown Source) ~[?:1.8.0_171]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_171]
	at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_171]
	at java.lang.String.format(Unknown Source) ~[?:1.8.0_171]
	at de.teamlapen.lib.lib.util.UtilLib.translateFormatted(UtilLib.java:533) [UtilLib.class:?]
	at de.teamlapen.vampirism.modcompat.guide.GuideBook.buildCreatures(GuideBook.java:307) [GuideBook.class:?]
	at de.teamlapen.vampirism.modcompat.guide.GuideBook.buildCategories(GuideBook.java:72) [GuideBook.class:?]
	at de.teamlapen.vampirism.modcompat.guide.GuideBook.handlePost(GuideBook.java:459) [GuideBook.class:?]
	at amerifrance.guideapi.GuideMod.postInit(GuideMod.java:62) [GuideMod.class:1.12-2.1.7-62]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:534) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3929) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at ru.squareland.launcher.csl.ZFYn5Z0BQlYw6195.main(Unknown Source) [csl.jar:?]

**Comment by maxanier** [comment]
Thank you for reporting. It looks like a translation String is incorrect.
Which language are you using in MC?

**Comment by avescarelo** [comment]
Russian

**Comment by maxanier** [comment]
Ok, thx. Will be fixed in next release.
