### ISSUE TITLE
Crash when players log out of server

### ISSUE THREAD

**Issue by Skiviper-AJM** [TeamLapen/Vampirism#524]
## Versions
- Minecraft: 1.14.4                   
- Forge: 28.1.26                      
- Vampirism: Vampirism-1.14.4-1.6.0-alpha+20190930-2052
                                            

## Issue Description
When running on a server, server crashes when a player logs out, even if the player has had no interaction with the mod. Near as i can tell its an issue with the mod checking if vampire on logout

## Reproduce Steps
Install on server with said version of forge, log in, log out.

## Additional Information
there are other mods on the server, but near as i can tell the crash report points to this mod in particular as the issue

---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/10/19 9:21 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at fr.zeamateis.damage_indicator.common.event.CommonEventHandler.onEntityHasPotionRemoved(CommonEventHandler.java:96) ~[?:0.0.6] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_205_CommonEventHandler_onEntityHasPotionRemoved_PotionRemoveEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraft.entity.LivingEntity.func_195063_d(LivingEntity.java:791) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:coremodmethod,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at de.teamlapen.vampirism.player.vampire.VampirePlayer.endFeeding(VampirePlayer.java:317) ~[?:1.6.0-alpha+20190930-2052] {re:classloading}
	at de.teamlapen.vampirism.player.vampire.VampirePlayer.onPlayerLoggedOut(VampirePlayer.java:626) ~[?:1.6.0-alpha+20190930-2052] {re:classloading}
	at de.teamlapen.lib.entity.EntityEventHandler.lambda$onPlayerLoggedOut$6(EntityEventHandler.java:106) ~[?:1.6.0-alpha+20190930-2052] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at de.teamlapen.lib.entity.EntityEventHandler.onPlayerLoggedOut(EntityEventHandler.java:106) ~[?:1.6.0-alpha+20190930-2052] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_543_EntityEventHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedOut(BasicEventHooks.java:48) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:291) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:900) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:367) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:153) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7350850904 bytes (7010 MB) / 8301576192 bytes (7917 MB) up to 8301576192 bytes (7917 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms6024M -Xmx8048M
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.26
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		AirHop-v1.1.1-1.14.4.jar Air Hop {airhop@1.1.1 DONE}
		allomancy-3.0.0-beta3.jar Allomancy {allomancy@3.0.0 DONE}
		Apotheosis-1.14.4-2.3.2.jar Apotheosis {apotheosis@2.3.2 DONE}
		BBOutlineReloaded-1.0.13b-1.14.4-forge.jar BoundingBoxOutlineReloaded {bbor@1.0.13-1.14.4 DONE}
		Better+Muffling-1.14.4-0.3.0-Beta.jar Better Muffling {bettermuffling@0.3.0-Beta DONE}
		bettertridentreturn-1.14.4-1.0.0.jar Better Trident Return {bettertridentreturn@1.0.0 DONE}
		caelus-FORGE-1.14.4-1.0.jar Caelus API {caelus@FORGE-1.14.4-1.0 DONE}
		CarryOn+MC1.14.4+v1.12.3.jar Carry On {carryon@1.12.3 DONE}
		ChickenDropFeathers-2.0.jar Chicken Drop Feathers {chickendropfeathersmod@2.0 DONE}
		chunkloader-1.14.4-1.0.0.jar Chunk Loader {chunkloader@1.14.4-1.0.0 DONE}
		clickmachine.jar Click Machine {clickmachine@2.0.0 DONE}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a DONE}
		create-mc1.14.4_v0.1.1.jar Create {create@0.1.1 DONE}
		curios-FORGE-1.14.4-1.0.jar Curios API {curios@FORGE-1.14.4-1.0 DONE}
		curiouselytra-FORGE-1.14.4-1.0.jar Curious Elytra {curiouselytra@FORGE-1.14.4-1.0 DONE}
		damage_indicator-0.0.6.jar Ama's Damage Indicator {damage_indicator@0.0.6 DONE}
		DoggyTalents-1.14.4-1.15.1.7-universal.jar Doggy Talents {doggytalents@1.15.1.7 DONE}
		Druidcraft-1.14-0.1.31.jar Druidcraft {druidcraft@0.1.12 DONE}
		DungeonCrawl-1.14.4-1.3.0.jar Dungeon Crawl {dungeoncrawl@1.3.0 DONE}
		dwmh-1.14.4-3.0.1.jar Dude! Where's my Horse? {dwmh@1.14.4-3.0.1 DONE}
		enchantslash-1.14.4-1.0.0.jar EnchantSlash {enchantslash@1.0.0 DONE}
		EnderMagnet-1.14.3-1.0.0.jar Ender Magnet {endermagnet@1.14.3-1.0.0 DONE}
		essentials-1.14.4-2.5.1.jar Essentials {essentials@1.14.4-2.5.1 DONE}
		extraanvils-2.1a.jar Extra Anvils {extraanvils@2.1a DONE}
		extrabows-v1.14.4+b6.jar Extra Bows {extrabows@v1.14.4 b6 DONE}
		farlanders-1.14.4-1.0.0.jar The Farlanders {farlanders@1.0.0 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		FleshToLeather-1.14.3-1.1.0.jar FleshToLeather {fleshtoleather@1.1.0 DONE}
		flexible_skills-1.14.4-1.1.4.jar Flexible Skills Mod {flexible_skills@1.1.4 DONE}
		ForgivingVoid_1.14.4-3.0.7.jar Forgiving Void {forgivingvoid@3.0.7 DONE}
		gravestone-1.15.1.jar Gravestone Mod {gravestone@1.15.1 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		inventorysorter-1.14.4-16.0.0.jar Simple Inventory Sorter {inventorysorter@16.0.0 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		ironshulkerboxes-1.14.4-3.1.12.jar Iron Shulker Boxes {ironshulkerbox@1.14.4-3.1.12 DONE}
		jei-1.14.4-6.0.0.13.jar Just Enough Items {jei@6.0.0.13 DONE}
		Kathairis-1.14.4-alpha-0.15.jar Kathairis {kathairis@0.15 DONE}
		LightOverlay-3.5.jar Light Overlay Forge {lightoverlay-forge@3.4 DONE}
		lycanitesmobs-1.14.4-2.1.0.2.jar Lycanites Mobs {lycanitesmobs@1.0 DONE}
		MCFurnace-1.14.4-DEV-1.3.2.jar MCFurnace {mcfurnace@1.3.0 DONE}
		metalbarrels-1.3c.jar Metal Barrels {metalbarrels@1.3c DONE}
		Placebo-1.14.4-2.2.1.jar Placebo {placebo@2.2.1 DONE}
		recall-1.14.4-1.0.jar Recall {recall@1.0 DONE}
		respawnablepets-1.0.5.1.jar Respawnable Pets {respawnablepets@1.0.5.1 DONE}
		sit-1.14.4-v1.2.3.jar Sit {sit@v1.2.3 DONE}
		speedyhoppers-1.14.4-1.0.5.jar Speedy Hoppers {speedyhoppers@1.14.4-1.0.5 DONE}
		structurize-0.10.175-ALPHA.jar Structurize {structurize@0.10.175-ALPHA DONE}
		minecolonies-0.10.406-ALPHA-universal.jar Minecolonies {minecolonies@0.10.406-ALPHA DONE}
		themidnight-0.4.5.jar The Midnight {midnight@0.4.5 DONE}
		TreeChoppin-1.14.4-1.2.0.jar TreeChoppin {treechoppin@1.2.0 DONE}
		u_team_core-1.14.4-2.7.0.129.jar U Team Core {uteamcore@2.7.0.129 DONE}
		upsizer-mc1.14.4-5.0b2.jar Upsizer {upsizer@5.0.0b2 DONE}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 DONE}
		Vampirism-1.14.4-1.6.0-alpha+20190930-2052.jar Vampirism {vampirism@1.6.0-alpha+20190930-2051 DONE, teamlapenlib@1.6.0-alpha+20190930-2051 DONE}
		XaerosWorldMap_1.4.10.1_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.4.10.1 DONE}
		YAMDA-4.0.1.jar YAMDA {yamda@4.0.1 DONE}
		forge-1.14.4-28.1.26-universal.jar Forge {forge@28.1.26 DONE}
		forge-1.14.4-28.1.26-server.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 2 / 20; [ServerPlayerEntity['alfiealfie'/570, l='world', x=-519.02, y=71.00, z=-196.22], ServerPlayerEntity['SirQue'/656, l='world', x=-577.32, y=71.00, z=-234.27]]
	Data Packs: mod:vampirism, mod:upsizer, mod:structurize, mod:sit, mod:recall, mod:minecolonies (incompatible), mod:lycanitesmobs, mod:kathairis, mod:flexible_skills, mod:farlanders, mod:extrabows, mod:extraanvils, mod:endermagnet, mod:enchantslash, mod:dungeoncrawl, mod:druidcraft, mod:create, mod:cosmeticarmorreworked, mod:clickmachine, mod:chickendropfeathersmod, mod:bettertridentreturn, mod:bettermuffling, mod:allomancy, mod:airhop, mod:bbor, mod:chunkloader, mod:curiouselytra, mod:curios, mod:fleshtoleather, mod:yamda, mod:xaeroworldmap, mod:uteamcore, mod:usefulbackpacks, mod:treechoppin, mod:speedyhoppers, mod:respawnablepets, mod:placebo, mod:midnight, mod:metalbarrels, mod:mcfurnace, mod:lightoverlay-forge, mod:jei, mod:ironshulkerbox, mod:ironchest, mod:inventorysorter, mod:harvest, mod:gravestone, mod:forgivingvoid, mod:forge, mod:fastleafdecay, mod:essentials, mod:dwmh, mod:doggytalents, mod:damage_indicator, mod:carryon, mod:caelus, mod:apotheosis, vanilla, file/logical-crafting (1).zip (incompatible), file/logical-crafting.zip (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by maxanier** [comment]
Unfortunately, I cannot reproduce the issue.
As far as I can tell it isn't caused by Vampirism but introduced by some other mod, it is merely triggered by Vampirism.
Ama-s Damage Indicator is somehow involved https://github.com/JibayMcs/Ama-s-Damage-Indicator/blob/a7e688e7d914657bd8179ae9125acac4b35f042e/src/main/java/fr/zeamateis/damage_indicator/common/event/CommonEventHandler.java#L94 but I can't see any faulty behaviour on their side either (player.world should be non null at that point of the logout process)

If have released an update that should minimize the chance of crashing (Only if a player logs out while slowness potion is active).
