### ISSUE TITLE
[Bug] Client crashes during start-up (issues with vampirism:converted_sheep)

### ISSUE THREAD

**Issue by icoop** [TeamLapen/Vampirism#532]
## Versions
- Minecraft:    1.14.4                
- Forge:         1.14.4-28.1.37             
- Vampirism:    1.6.0-alpha+20190930-2051                                         

## Issue Description
Game is crashing during client startup

## Reproduce Steps
Run game?

## Additional Information
The server is running successfully and the mods are shown in the Mods option in the client screen.  After loading the game it crashes due to a NullPointerException when trying to initialize the vampirism:converted_sheep object.

Client crash report:"
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 10/5/19 11:15 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at de.teamlapen.vampirism.entity.converted.ConvertedCreatureEntity.getConvertedHelper(ConvertedCreatureEntity.java:224) ~[?:1.6.0-alpha+20191001-1338] {re:classloading}
	at de.teamlapen.vampirism.entity.converted.ConvertedCreatureEntity.updateEntityAttributes(ConvertedCreatureEntity.java:275) ~[?:1.6.0-alpha+20191001-1338] {re:classloading}
	at de.teamlapen.vampirism.entity.converted.ConvertedCreatureEntity.func_70030_z(ConvertedCreatureEntity.java:93) ~[?:1.6.0-alpha+20191001-1338] {re:classloading}
	at de.teamlapen.vampirism.entity.converted.ConvertedSheepEntity.func_70030_z(ConvertedSheepEntity.java:39) ~[?:1.6.0-alpha+20191001-1338] {re:classloading}
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1964) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at de.teamlapen.vampirism.entity.VampirismEntity.func_70071_h_(VampirismEntity.java:212) ~[?:1.6.0-alpha+20191001-1338] {re:classloading}
	at de.teamlapen.vampirism.entity.converted.ConvertedCreatureEntity.func_70071_h_(ConvertedCreatureEntity.java:193) ~[?:1.6.0-alpha+20191001-1338] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:165) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$3255/372017580.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:133) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1343) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:868) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.37.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$343/732597634.call(Unknown Source) [forge-1.14.4-28.1.37.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.teamlapen.vampirism.entity.converted.ConvertedCreatureEntity.getConvertedHelper(ConvertedCreatureEntity.java:224)
	at de.teamlapen.vampirism.entity.converted.ConvertedCreatureEntity.updateEntityAttributes(ConvertedCreatureEntity.java:275)
	at de.teamlapen.vampirism.entity.converted.ConvertedCreatureEntity.func_70030_z(ConvertedCreatureEntity.java:93)
	at de.teamlapen.vampirism.entity.converted.ConvertedSheepEntity.func_70030_z(ConvertedSheepEntity.java:39)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:364)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1964)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at de.teamlapen.vampirism.entity.VampirismEntity.func_70071_h_(VampirismEntity.java:212)
	at de.teamlapen.vampirism.entity.converted.ConvertedCreatureEntity.func_70071_h_(ConvertedCreatureEntity.java:193)
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:165)
	at net.minecraft.client.world.ClientWorld$$Lambda$3255/372017580.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: vampirism:converted_sheep (de.teamlapen.vampirism.entity.converted.ConvertedSheepEntity)
	Entity ID: 47
	Entity Name: TranslatableComponent{key='entity.vampirism.vampire.name', args=[], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}} TranslatableComponent{key='entity.minecraft.sheep', args=[], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
	Entity's Exact location: 261.24, 69.00, -17.58
	Entity's Block location: World: (261,69,-18), Chunk: (at 5,4,14 in 16,-2; contains blocks 256,0,-32 to 271,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:133)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Luceandgoose'/218, l='MpServer', x=184.50, y=68.00, z=-159.50]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (176,64,-160), Chunk: (at 0,4,0 in 11,-10; contains blocks 176,0,-160 to 191,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 12783 game time, 19008015 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$343/732597634.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 835098560 bytes (796 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.37.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.37
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		Vampirism-Mod-1.14.4.jar Vampirism {vampirism@1.6.0-alpha+20190930-2051 DONE, teamlapenlib@1.6.0-alpha+20190930-2051 DONE}
		forge-1.14.4-28.1.37-universal.jar Forge {forge@28.1.37 DONE}
		forge-1.14.4-28.1.37-client.jar Minecraft {minecraft@1.14.4 DONE}
	Launched Version: 1.14.4-forge-28.1.37
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz

**Comment by maxanier** [comment]
Didn't mean to close it yet.

Uploaded a version, which should fix this issue. Can you check that?

**Comment by icooptableau** [comment]
I was able to download and run the uploaded version with no issues.  Thank you!
