### ISSUE TITLE
[Bug] 1.15.2[31.1.18-forge] Cant log back into server after being bitten by vampire

### ISSUE THREAD

**Issue by SDUBZ** [TeamLapen/Vampirism#622]
- Minecraft: 1.15.2                   
- Forge: 31.1.18                       
- Vampirism: Vampirism-1.15.2-1.6.0-alpha+20200228-0048                                             

## Issue Description
I was playing on my server and suddenly got bitten this kick me off straight away but eventually it gave a error after i got kicked and wouldnt allow me back on

## Reproduce Steps
i guess by getting bitten on a server is the way 

I thought i would include my pack so if you needed to test out of a dev enviroment you could goto the server get bitten see what happens yourself 
https://www.curseforge.com/minecraft/modpacks/forager-pack
Logs:
[latest.log](https://github.com/TeamLapen/Vampirism/files/4301210/latest.log)
[debug.log](https://github.com/TeamLapen/Vampirism/files/4301211/debug.log)

**Comment by maxanier** [comment]
This is caused by some mod messing up the data pack loading

```
[06Mar2020 06:36:06.861] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Attempted to load class net/minecraftforge/resource/ReloadRequirements for invalid dist DEDICATED_SERVER
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_222]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1467) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:363) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraftforge/resource/ReloadRequirements for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.15.2-31.1.18.jar:31.1]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:103) ~[modlauncher-5.0.0-milestone.4.jar:5.0.0-milestone.4+67+b1a340b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) ~[modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) ~[modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	at net.minecraftforge.resource.SelectiveReloadStateHandler.get(SelectiveReloadStateHandler.java:64) ~[?:?]
	at net.minecraftforge.resource.ISelectiveResourceReloadListener.func_195410_a(ISelectiveResourceReloadListener.java:33) ~[?:?]
	at net.minecraft.resources.IResourceManagerReloadListener.lambda$reload$0(IResourceManagerReloadListener.java:16) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_222]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_222]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?]
```

Unfortunately, I am not able to identify the mod (there are many in the pack).

This does not only cause the reconnect issue, but should also result in many other issues (not just for Vampirism but also other mods).

However, I will have a look if I can at least allow you to reconnect (even though there isn't really a point of playing with this issue)

**Comment by maxanier** [comment]
I have added a workaround/fix for the connection problem (Will upload new alpha later today).

However, as I said, there isn't really a point in playing as long as the problematic mod is present.
For Vampirism skills won't work, entities won't be biteable and other issues will occur.

**Comment by SDUBZ** [comment]
ok thank you for you can do, wish i could narrow down the actual mod causing this but even the debug logs dont trace back to where it comes from either

**Comment by maxanier** [comment]
The log is indeed quite useless. 
I have created an issue for Forge https://github.com/MinecraftForge/MinecraftForge/issues/6553
but I wouldn't expect anything to happen there soon.

Only thing you can do is probably remove mods one by one (most likely a recently updated mod or a less popular mod that is causing this)

**Comment by SDUBZ** [comment]
yeah might have to do that soon but this is only happening server side

**Comment by SDUBZ** [comment]
found 2 mods but one hasnt been patched yet so if you get a repeat of this check to see if the user has the interior mod running server side

**Comment by maxanier** [comment]
thank you investigating and letting us know
