### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by chriss0612** [TeamLapen/Vampirism#69]
I get an error message like this when starting the server(1.9-Forge-12.16.0.1866) with vampirism installed:

[17:55:49] [Thread-9/INFO] [teamlapen-lib]: [VersionChecker]Starting version check at https://raw.githubusercontent.com/TeamLapen/Vampirism/master/src/main/resources/versions.json
[17:55:49] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[17:55:49] [Server thread/ERROR] [FML]:
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHI    mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
        UCHI    FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1866-1.9-universal.jar)
        UCHI    Forge{12.16.0.1866} [Minecraft Forge] (forge-1.9-12.16.0.1866-1.9-universal.jar)
        UCHI    autopackager{1.6.1} [AutoPackager] (autopackager-1.6.1.jar)
        UCHI    Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar)
        UCHI    baublesstuff{2.0.6} [Baubles Stuff] (baublesstuff-2.0.6.jar)
        UCHI    guideapi{1.9-2.0.0-30} [Guide-API] (Guide-API-1.9-2.0.0-30.jar)
        UCHI    BloodMagic{1.9-2.0.0-35} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-35.jar)
        UCHI    Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9-1.4.1.jar)
        UCHI    bookshelf{1.2.0.226} [Bookshelf] (Bookshelf-1.9-1.2.0.237.jar)
        UCHI    bookshelfapi{3.0.4} [Bookshelf] (Bookshelf-API-1.9-3.0.4.jar)
        UCHI    Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar)
        UCHI    chiselsandbits{9.14} [Chisels & Bits] (chiselsandbits-9.14.jar)
        UCHI    compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.9-rc.jar)
        UCHI    cookingforblockheads{2.0.5} [Cooking for Blockheads] (CookingForBlockheads-mc1.9-2.0.5.jar)
        UCHI    ElecCore{1.4.270} [ElecCore] (ElecCore-1.9-1.4.270.jar)
        UCHI    deepresonance{1.1.4beta30} [DeepResonance] (deepresonance-1.9.0-1.1.4beta30.jar)
        UCHI    eplus{4.1.0.86} [Enchanting Plus] (EnchantingPlus-1.9-4.1.0.97.jar)
        UCHI    fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar)
        UCHI    graves{1.9-b10-universal} [Graves Mod] (graves-1.9-b10-universal.jar)
        UCHI    mantle{1.9-0.9.4.jenkins114} [Mantle] (Mantle-1.9-0.9.4.jar)
        UCHI    tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct] (TConstruct-1.9-2.2.2.jar)
        UCHI    neotech{3.0.6} [NeoTech] (NeoTech-1.9-3.0.6.jar)
        UCHI    fodc{1.8.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.1.jar)
        UCHI    Psi{beta-31} [Psi] (Psi-beta-31.jar)
        UCHI    randomthings{3.7} [Random Things] (RandomThings-MC1.9-3.7.jar)
        UCHI    xreliquary{1.9-1.3.1.322} [Reliquary] (Reliquary-1.9-1.3.1.322.jar)
        UCHI    rftools{4.45} [RFTools] (rftools-1.9.0-4.45.jar)
        UCHI    rftoolsdim{4.23beta37} [RFTools Dimensions] (rftoolsdim-1.9.0-4.23beta37.jar)
        UCHI    Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar)
        UCHI    soulshardstow{1.9-2.3.9-25} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9-2.3.9-25.jar)
        UCHI    StorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar)
        UCHE    vampirism{1.0.0-Alpha+04-29-16-14} [Vampirism] (Vampirism-1.9-1.0.0-Alpha+04-29-16-14.jar)
        UCHI    teamlapen-lib{1.0.0-Alpha+04-29-16-14} [TeamLapen Library] (Vampirism-1.9-1.0.0-Alpha+04-29-16-14.jar)
[17:55:50] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[17:55:50] [Server thread/ERROR] [FML]: Caught exception from vampirism
java.lang.NoClassDefFoundError: de/teamlapen/vampirism/client/render/particle/ModParticles
        at de.teamlapen.vampirism.proxy.CommonProxy.onInitStep(CommonProxy.java:25) ~[CommonProxy.class:?]
        at de.teamlapen.vampirism.proxy.ServerProxy.onInitStep(ServerProxy.java:24) ~[ServerProxy.class:?]
        at de.teamlapen.vampirism.VampirismMod.init(VampirismMod.java:125) ~[VampirismMod.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:102) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) [la.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: de.teamlapen.vampirism.client.render.particle.ModParticles
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
        ... 34 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4b6690c0 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
        ... 34 more
Caused by: java.lang.RuntimeException: Attempted to load class de/teamlapen/vampirism/client/render/particle/ModParticles for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
        ... 34 more
[17:55:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: de/teamlapen/vampirism/client/render/particle/ModParticles

        at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:102) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) ~[la.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NoClassDefFoundError: de/teamlapen/vampirism/client/render/particle/ModParticles
        at de.teamlapen.vampirism.proxy.CommonProxy.onInitStep(CommonProxy.java:25) ~[CommonProxy.class:?]
        at de.teamlapen.vampirism.proxy.ServerProxy.onInitStep(ServerProxy.java:24) ~[ServerProxy.class:?]
        at de.teamlapen.vampirism.VampirismMod.init(VampirismMod.java:125) ~[VampirismMod.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737) ~[Loader.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: de.teamlapen.vampirism.client.render.particle.ModParticles
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
        at de.teamlapen.vampirism.proxy.CommonProxy.onInitStep(CommonProxy.java:25) ~[CommonProxy.class:?]
        at de.teamlapen.vampirism.proxy.ServerProxy.onInitStep(ServerProxy.java:24) ~[ServerProxy.class:?]
        at de.teamlapen.vampirism.VampirismMod.init(VampirismMod.java:125) ~[VampirismMod.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737) ~[Loader.class:?]
        ... 5 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4b6690c0 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
        at de.teamlapen.vampirism.proxy.CommonProxy.onInitStep(CommonProxy.java:25) ~[CommonProxy.class:?]
        at de.teamlapen.vampirism.proxy.ServerProxy.onInitStep(ServerProxy.java:24) ~[ServerProxy.class:?]
        at de.teamlapen.vampirism.VampirismMod.init(VampirismMod.java:125) ~[VampirismMod.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737) ~[Loader.class:?]
        ... 5 more
Caused by: java.lang.RuntimeException: Attempted to load class de/teamlapen/vampirism/client/render/particle/ModParticles for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
        at de.teamlapen.vampirism.proxy.CommonProxy.onInitStep(CommonProxy.java:25) ~[CommonProxy.class:?]
        at de.teamlapen.vampirism.proxy.ServerProxy.onInitStep(ServerProxy.java:24) ~[ServerProxy.class:?]
        at de.teamlapen.vampirism.VampirismMod.init(VampirismMod.java:125) ~[VampirismMod.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.9-12.16.0.1866-1.9-universal.jar:?]
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737) ~[Loader.class:?]
        ... 5 more
[17:55:51] [Server thread/ERROR]: This crash report has been saved to: D:\Server(1.9)\.\crash-reports\crash-2016-05-02_17.55.51-server.txt
[17:55:51] [Server thread/INFO]: Stopping server
[17:55:51] [Server thread/INFO]: Saving worlds
[17:55:51] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[17:55:51] [Server thread/INFO] [mcjty.lib.varia.Logging]: Deep Resonance: server is stopping. Shutting down gracefully
[17:55:51] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[17:55:51] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[17:55:51] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[17:55:51] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
[17:55:51] [Server Shutdown Thread/INFO]: Stopping server

**Comment by maxanier** [comment]
Thanks for the report. I've already fixed that, but forgot to upload the fixed versions. I will do so as soon as I'm finished with setting up my development environment again.

**Comment by maxanier** [comment]
Fixed version available on CurseForge
