### ISSUE TITLE
[Bug] [1.16.1] Save inaccessible after I died as a Vampire

### ISSUE THREAD

**Issue by ghost** [TeamLapen/Vampirism#748]
## Versions
- Minecraft: 1.16.1                
- Forge: 32.0.88                    
- Vampirism: 1.6.0-alpha+20200726-0933                                           

- ModPack: N/A

## Issue Description
After I died for the first time being a vampire and respawned my game crashed and now I can't play that save.

## Additional Information
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 29/07/20 22:46
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.event.entity.player.PlayerEvent$NameFormat.getDisplayname()Ljava/lang/String;
	at de.teamlapen.vampirism.player.ModPlayerEventHandler.lambda$onPlayerName$5(ModPlayerEventHandler.java:261) ~[?:1.6.0-alpha+20200726-0933] {re:classloading}
	at de.teamlapen.vampirism.player.ModPlayerEventHandler$$Lambda$7430/860971329.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at de.teamlapen.vampirism.player.ModPlayerEventHandler.onPlayerName(ModPlayerEventHandler.java:258) ~[?:1.6.0-alpha+20200726-0933] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_230_ModPlayerEventHandler_onPlayerName_NameFormat.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.getPlayerDisplayName(ForgeEventFactory.java:251) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_145748_c_(PlayerEntity.java:1748) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:vampirism:player_attributes,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:vampirism:playersize,xf:fml:caelus:coremodone}
	at net.minecraft.entity.Entity.func_195051_bN(Entity.java:2614) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:immersiveengineering:IE wire damage}
	at net.minecraft.command.Commands.func_197051_a(Commands.java:270) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_187245_a(PlayerList.java:582) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_187243_f(PlayerList.java:476) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:158) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:133) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:121) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6810/76653583.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4090022376 bytes (3900 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.88.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.88.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.88.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.88.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.1_HD_U_G2_pre5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.88.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.88
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.88-client.jar Minecraft {minecraft@1.16.1 DONE}
		Lucky-Block-Mod-1.16.1.jar Lucky Block {lucky@1.16.1-1 DONE}
		Bookshelf-1.16.1-6.1.11.jar Bookshelf {bookshelf@6.1.11 DONE}
		EnchantmentDescriptions-1.16.1-3.0.2.jar EnchantmentDescriptions {enchdesc@3.0.2 DONE}
		ImmersiveEngineering-0.16-109.jar Immersive Engineering {immersiveengineering@0.16-109 DONE}
		u_team_core-1.16.1-3.1.1.163-SNAPSHOT.jar U Team Core {uteamcore@3.1.1.163-SNAPSHOT DONE}
		BiomesOPlenty-1.16.1-11.0.0.387-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.387 DONE}
		xray-1.16.1-2.3.2.jar Advanced XRay {xray@2.3.2 DONE}
		Vampirism-1.16.1-1.6.0-alpha+20200726-0933.jar Vampirism {vampirism@1.6.0-alpha+20200726-0933 DONE, teamlapenlib@1.6.0-alpha+20200726-0933 DONE}
		curiouselytra-FORGE-1.16.1-3.0.jar Curious Elytra {curiouselytra@FORGE-1.16.1-3.0 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		Abnormals-Core-1.16.1-v2.0.0.jar Abnormals Core {abnormals_core@2.0.0 DONE}
		Buzzier-Bees-1.16.1-2.0.0.jar Buzzier Bees {buzzier_bees@2.0.0 DONE}
		VampiresNeedUmbrellas-1.16.1-1.0.jar Vampires Need Umbrellas {vampiresneedumbrellas@1.0 DONE}
		craftablehorsearmour-1.3.jar Craftable Horse Armour {craftablehorsearmour@1.3 DONE}
		caelus-FORGE-1.16.1-2.0-beta5.jar Caelus API {caelus@FORGE-1.16.1-2.0-beta5 DONE}
		forge-1.16.1-32.0.88-universal.jar Forge {forge@32.0.88 DONE}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		RingsOfAscension-1.16.1-1.5.3.jar Rings of Ascension {ringsofascension@1.5.3 DONE}
		invtweaks-1.16.1-1.0.5.jar Inventory Tweaks Renewed {invtweaks@1.16.1-1.0.5 DONE}
		curios-FORGE-1.16.1-3.0-beta4.jar Curios API {curios@FORGE-1.16.1-3.0-beta4 DONE}
		Xaeros_Minimap_20.16.0.1_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.16.0 DONE}
		pamhc2foodcore-1.16.1-1.0.5.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		Artifacts-1.16.1-2.2.0.jar Artifacts {artifacts@1.16.1-2.2.0 DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:lucky (incompatible), mod:bookshelf (incompatible), mod:enchdesc (incompatible), mod:immersiveengineering (incompatible), mod:uteamcore, mod:biomesoplenty, mod:xray (incompatible), mod:vampirism (incompatible), mod:curiouselytra (incompatible), mod:jei (incompatible), mod:abnormals_core, mod:buzzier_bees, mod:vampiresneedumbrellas (incompatible), mod:craftablehorsearmour (incompatible), mod:caelus (incompatible), mod:forge, mod:appleskin, mod:ringsofascension, mod:invtweaks (incompatible), mod:curios (incompatible), mod:xaerominimap, mod:pamhc2foodcore (incompatible), mod:ironchest, mod:artifacts
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre5
	OptiFine Build: 20200719-015630
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by maxanier** [comment]
Pls update to the latest alpha
