### ISSUE TITLE
[Bug][1.16.4][DS] sundamageDisabledBiomes crashing on load on dedicated server

### ISSUE THREAD

**Issue by drakray** [TeamLapen/Vampirism#820]
## Versions
- Minecraft: 1.16.4
- Forge: 35.1.13
- Vampirism: 1.16.4-1.7.0

- ModPack: N/A

## Issue Description
Trying to set some biomes in sundamageDisabledBiomes, get a crash on dedicated server, but not on solo playing

## Reproduce Steps
Uses OhTheBiomesYoullGo, BiomesOPlenty, Quark
<details><summary>Set vampirism-server to</summary>

```
sundamageDisabledBiomes = ["byg:bayou","byg:glowshroom_bayou","biomesoplenty:bayou","biomesoplenty:deep_bayou","biomesoplenty:bayou_mangrove","biomesoplenty:ominous_woods","biomesoplenty:ominous_mire","biomesoplenty:mystic_grove","biomesoplenty:dead_forest","byg:enchanted_forest","byg:enchanted_forest_hills","byg:enchanted_grove","byg:flowering_enchanted_grove","byg:the_black_forest","byg:black_forest_clearing","byg:black_forest_hills","biomesoplenty:wasteland","biomesoplenty:dry_boneyard","biomesoplenty:burnt_forest","biomesoplenty:silkglade_nest","biomesoplenty:mystic_plains","biomesoplenty:dead_swamp","biomesoplenty:silkglade","byg:weeping_witch_clearing","byg:bog","byg:pumpkin_forest","byg:twilight_valley_hills","byg:twilight_valley","byg:dead_sea","byg:ancient_forest","byg:glowing_ancient_forest","byg:flowering_ancient_forest"]
```

</details>

Try to open a dedicated server.
I can provide my personal modPack if necessary to reproduce

## Additional Information
https://pastebin.com/KPbVmspX
<details><summary>Snippet for easy searching</summary>

```
java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.func_217855_b(Ljava/lang/String;)Z
	at de.teamlapen.vampirism.config.VampirismConfig$Server.lambda$new$0(VampirismConfig.java:155) ~[vampirism:1.7.0] {re:classloading}
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline.allMatch(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.common.ForgeConfigSpec$Builder.lambda$defineList$5(ForgeConfigSpec.java:317) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec$ValueSpec.test(ForgeConfigSpec.java:680) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec.correct(ForgeConfigSpec.java:191) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec.correct(ForgeConfigSpec.java:160) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec.correct(ForgeConfigSpec.java:160) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec.isCorrect(ForgeConfigSpec.java:121) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec.setConfig(ForgeConfigSpec.java:84) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ModConfig.setConfigData(ModConfig.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:105) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[forge:?] {re:classloading}
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_271] {re:computing_frames}
	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:95) ~[forge:?] {re:mixin,re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:620) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
```

</details>

**Comment by drakray** [comment]
Even just ```sundamageDisabledBiomes = ["byg:bayou"]``` make the crash on DS

**Comment by drakray** [comment]
Crash may be caused by ```sundamageDimensionsOverridePositive = ["rats:ratlantis"]``` or ```sundamageDimensionsOverrideNegative = ["undergarden:undergarden"]``` too.
