### ISSUE TITLE
[Modcompat] Baked Blood Container and Better Foliage

### ISSUE THREAD

**Issue by yanoreki** [TeamLapen/Vampirism#923]
## Versions

- Minecraft: 1.14.4
- Forge:  28.2.0
- Vampirism: 1.7.1
- Incompatible mod: Better Foliage 2.5.0
- Link to mod: https://www.curseforge.com/minecraft/mc-mods/better-foliage/files/2862537

- ModPack: N/A

## Issue Description
When you put Baked Blood Container-the game crashes.
If the dungeon with Baked Blood Container is loaded, it also crashes.

## Reproduce Steps
Take the Baked Blood Container from the creative and put it on.

## Additional Information
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at de.teamlapen.vampirism.client.model.blocks.BakedBloodContainerModel.getQuads(BakedBloodContainerModel.java:91) ~[?:1.7.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:137) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:88) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:89) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28) ~[?:2.5.0] {re:classloading}
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102) ~[?:2.5.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:1015) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:385) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:229) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_215320_a(WorldRenderer.java:1425) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:1152) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:1037) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:795) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.0.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$450/1179272258.call(Unknown Source) [forge-1.14.4-28.2.0.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.teamlapen.vampirism.client.model.blocks.BakedBloodContainerModel.getQuads(BakedBloodContainerModel.java:91)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:137)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:88)

-- Block model being tesselated --
Details:
	Block: Block{vampirism:blood_container}
	Block location: World: (-139,64,-36), Chunk: (at 5,4,12 in -9,-3; contains blocks -144,0,-48 to -129,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:95)

-- Block being tesselated --
Details:
	Block: Block{vampirism:blood_container}
	Block location: World: (-139,64,-36), Chunk: (at 5,4,12 in -9,-3; contains blocks -144,0,-48 to -129,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:89)
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69)
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30)
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102)
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:1015)
	at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:385)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:229)
	at net.minecraft.client.renderer.WorldRenderer.func_215320_a(WorldRenderer.java:1425)
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:1152)
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:1037)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['0reki_'/324, l='MpServer', x=-139.06, y=64.13, z=-36.63]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-144,64,-44), Chunk: (at 0,4,4 in -9,-3; contains blocks -144,0,-48 to -129,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 278 game time, 278 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$450/1179272258.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3470980640 bytes (3310 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.0.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.0.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.0.jar mixinbootstrap PLUGINSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		Vampirism-1.14.4-1.7.1.jar Vampirism {vampirism@1.7.1 DONE, teamlapenlib@1.7.1 DONE}
		BetterFoliage-2.5.0-Forge-1.14.4.jar Better Foliage {betterfoliage@2.5.0 DONE}
	Launched Version: 1.14.4-forge-28.2.0
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.79, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

**Comment by maxanier** [comment]
Thank you for reporting. This seems to be a more or less common issue with BetterFoliage, which does not seem to be maintained anymore. https://github.com/octarine-noise/BetterFoliage/issues/293 https://github.com/octarine-noise/BetterFoliage/issues/286
I will have a look to see if we can fix this on our end or at least implement a workaround

**Comment by yanoreki** [comment]
Bug fixed in the new version of the Better Foliage mod - https://www.curseforge.com/minecraft/mc-mods/better-foliage/files/3295739
